plugins/org.eclipse.n4js.ui/contents/GH_10_TODO.txt

This place-holder file is required, because otherwise builds will fail due to a missing folder.
NOTE: merging this PR does *not* resolve #10 !

#10: add place-holder file for CQ-13814

---

plugins/org.eclipse.n4js.xpect/src/org/eclipse/n4js/xpect/methods/scoping/N4JSCommaSeparatedValuesExpectation.java
plugins/org.eclipse.n4js.xpect/src/org/eclipse/n4js/xpect/methods/scoping/ScopeXpectMethod.java

__Task:__ https://github.com/eclipse/n4js/issues/8
Also-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

GH-8: As a smith I need two Xpect related files in N4JS repository

---

plugins/org.eclipse.n4js.xpect/src/org/eclipse/n4js/xpect/methods/scoping/N4JSCommaSeparatedValuesExpectation.java
plugins/org.eclipse.n4js.xpect/src/org/eclipse/n4js/xpect/methods/scoping/ScopeXpectMethod.java

In `ScopeXpectMethod` and `N4JSCommaSeparatedValuesExpectation` fixed
* package declarations
* import statements

#12 GH-12 fixed compilation errors in the new Xpect files

---

tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/parser/ES_07_09_AutomaticSemicolonInsertionParserTest.xtend

The single commit of this PR re-applies a change* that was part of PR #7 which was
accidentally reverted in PR #17.
for original change see: https://github.com/eclipse/n4js/pull/7/commits/a409637a3dcbe97d373b40c3f71550ea368e882f

#16: Recent changes by N4JS committers (correction)

---

docs/org.eclipse.n4js.spec/chapters/05_classifiers/classifiers-part-02-members.adoc

This PR documents the restrictions when initializing interface fields in n4jsd and is a complement to the PR done for https://github.com/NumberFour/n4js/issues/388

GHOLD-388: Document restrictions when initializing interface fields in n4jsd

---

n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.ide/messages.md
plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft.reporter.ide/messages.md

__Task https://github.com/eclipse/n4js/issues/81__

#81: Fix syntax of copyright header comments in markdown files

---

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/N4JSStylers.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/helper/LabelCalculationHelper.xtend
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/helper/StyledTextCalculationHelper.xtend
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/outline/N4JSOutlineTreeProvider.xtend
tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/outline/N4JSOutlineWorkbenchPluginUITest.xtend

#124 , follow up (bug) of #99 
removed all AST access in outline view related label providers

#124: omit AST access if possible (in the context of outline view)

---

plugins/org.eclipse.n4js.smith.graph/src/org/eclipse/n4js/smith/graph/EMFGraphProvider.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/organize/imports/DocumentImportsOrganizer.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTProcessor.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSPostProcessor.java
testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/N4JSValidationTestHelper.java
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralParam_01.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralParam_02.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralParam_03.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralParam_04.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralParam_05.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralReturn_01.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralReturn_02.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralReturn_03.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralReturn_04.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/CastToFunctionWithStructuralReturn_05.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/postProcessing/references/ReferencedClassA.n4js

fix #146 
* tests for the issue
* make `ASTProcessor` traverse inherited references
* in general small adjustment when traversing references to avoid going to the parent
* some imports cleaned up

#146 fix resolving references to the structural types

---

plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft.reporter.ide/src-gen/es/org.eclipse.n4js.mangelhaft.reporter.ide/org/eclipse/n4js/mangelhaft/reporter/ide/IDEReporter.js
plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft.reporter.ide/src/n4js/org/eclipse/n4js/mangelhaft/reporter/ide/IDEReporter.n4js

This is the UpdateShippedCode changes that I missed to execute another time after I made a change to IDEReporter.n4js.

Update shipped code following mangelhaft FQN changes

---

n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.ide/src/n4js/org/eclipse/n4js/mangelhaft/reporter/ide/IDEReporter.n4js
plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft.reporter.ide/src-gen/es/org.eclipse.n4js.mangelhaft.reporter.ide/org/eclipse/n4js/mangelhaft/reporter/ide/IDEReporter.js
plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft.reporter.ide/src/n4js/org/eclipse/n4js/mangelhaft/reporter/ide/IDEReporter.n4js
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/resources/BaseResource.java
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/resources/ResourceRouterServlet.java
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/resources/service/TestCatalogAssemblerResource.java
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/resources/tests/StartTestResource.java
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/resources/tests/TestResource.java
tests/org.eclipse.n4js.hlc.tests/probands/testers/DemoTest/test/subfolder/SubFolderModule.n4js
tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscTestersTest.java
tests/org.eclipse.n4js.tester.tests/src/org/eclipse/n4js/tester/tests/LoggingMockResourceTesterModule.java
tests/org.eclipse.n4js.tester.tests/src/org/eclipse/n4js/tester/tests/resource/TestIdParsingTest.xtend

As discussed I changed the escaping of FQNs in mangelhaft IDE reporter URLs to standard URL-escaping.

GH-171:  Use URL-encoding for FQNs in mangelhaft IDE reporter URLs

---

plugins/org.eclipse.n4js.n4jsx.ui/plugin.xml
plugins/org.eclipse.n4js.n4mf.ui/plugin.xml
plugins/org.eclipse.n4js.regex.ui/plugin.xml
plugins/org.eclipse.n4js.ts.ui/plugin.xml
plugins/org.eclipse.n4js.ui/plugin.xml

Issue: https://github.com/eclipse/n4js/issues/177
The Quick Access Search could cause NPEs since the actual editors are initialised lazily. If we don't provide an icon in the plugin.xml files, the Eclipse platform can't find an icon for inactive background editors. 
This is not handled in the QuickAccessEntry creation which can lead to NPEs.
In this PR I added icons to all our editors in their plugin.xml files. The icon I used is the one the default XtextEditor provides. To be found under platform:/plugin/org.eclipse.ui/icons/full/obj16/file_obj.png.
This change also means that on startup, all editor tabs will have a nice icon in their title even if they haven't been loaded yet.
Also please don't forget about the internal PR.
For builds see internal PR.

GH-177: Add icons for all editors in their plugin.xml files

---

builds/org.eclipse.n4js.product.build/N4JS__IDE.launch
docs/org.eclipse.n4js.spec/chapters/08_expressions/expressions.adoc
plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypingStrategyFilter.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSClassValidator.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSTypeValidator.xtend
tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GHOLD_0214_SpecCtorsWithPublicInternalInconsistency.n4js.xt
tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/IDEBUG_0113_OptionalFieldsWithCtorExecTest.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-pending/matrix/Class_x_ST_US/01_instantiation.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-pending/matrix/Ctor_x_AnnoReadonly/03_anon_interface.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Class_x_ST_DS/04_default_n_static.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Class_x_ST_US/07_static_n_default.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Class_x_ST_US/09_nested_ST_members.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Ctor_x_AnnoSpec/02_spec_access.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Enum/ST.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Interface_x_ST_DS/02_as_return_value.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Lambda/07_ST_class.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Lambda/07_ST_function.n4js.xt
tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Lambda/07_ST_interface.n4js.xt
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_02_02_01__StructuralThisTypeInCtorAndSpecParameter/Constraints_55_9_Structural_Fields_Can_Be_Assigned_Via_Public_Accessors.n4js.xt
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_02_02_01__StructuralThisTypeInCtorAndSpecParameter/IDEBUG_0262_struc_this_calling_super_ctor--usage.n4js.xt
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_02_02_01__StructuralThisTypeInCtorAndSpecParameter/Req59_4_AdditionalFieldsInSpecCtor.n4js.xt
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_02_02_01__StructuralThisTypeInCtorAndSpecParameter/Req59_8_Spec_Constructor_Ignores_Superfluous_Properties.n4js.xt
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch08_01_05_ObjectLiteral/ObjectLiteral_SuperfluousProperties.n4js.xt
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch08_02_01_SuperKeyword/SuperCall.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/typemodifier/optional_field_getter_setter.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/typemodifier/optional_getterSetterFieldCombinations.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/typesystem/AT_691_structuralTypingThisAndObjectLiteral.n4js.xt
tests/org.eclipse.n4js.xpect.tests/model/typesystem/GHOLD_0004_StructuralSubtypingMatrix.n4js.xt

#225 
This replaces old validation of superfluous properties in spec constructors, as that becomes a special case of this more general solution.

#225: added warning if object literal contains superfluous properties

---

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/dialog/ModuleSpecifierSelectionDialog.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/workspace/WorkspaceWizardModel.xtend

See #269.
Fixes four exceptions that were thrown during the execution of SWTBot tests. One of them caused the test to fail sometimes.
- Exception due to logging when shutdown.
- Exception due to synchronisation on UI thread.
- Exception due to URI.createPlatformResourceURI("", true);
- Exception due to new Path creation with null value

#269: Fix sometimes failing SWTBot tests and exceptions that are thrown in passed SWTBot tests

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NodeProcessBuilder.java

this updates `npm cache clean` command with the `--force` option - required as of npm 5.0.0

#278 add '--force' flag to the npm cache clean action

---

builds/org.eclipse.n4js.headless.product.build/org.eclipse.n4js.headless.product.product
tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/FileUtils.java
tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java

see #301 
This PR makes initialization of registers (the fallback for the extension points) conditional to the status of the Eclipse platform.
In short: when N4JSC.jar runs as OSGI application, do not re initialize extension points, especially the runners and testers.

GH-301 avoid double initialization of registers (e.g. runners and testers) in N4JSC.jar

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/CanLoadFromDescriptionHelper.java
tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/scoping/CircularReferencesScopingTest.xtend
tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/dirtystate/CanLoadFromDescriptionCyclicPluginUITest.xtend
tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/dirtystate/CanLoadFromDescriptionPluginUITest.xtend

Merging this will temporarily disable the CanLoadFromDescriptionHelper, i.e. all dependencies will be loaded from Xtext index, none from AST (the old behavior).

IDE-2896: Experimental: turn off canLoadFromDescription logic

---

plugins/org.eclipse.n4js.n4mf/src/org/eclipse/n4js/n4mf/validation/N4MFValidator.xtend
plugins/org.eclipse.n4js.n4mf/src/org/eclipse/n4js/n4mf/validation/WildcardPathFilter.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/AbstractN4JSCore.java

Changes to project paths scanning when handling module filters, i.e. ignore non source paths.

GH-366 Unnecessary scanning of the non source paths when wildcards are defined

---

plugins/org.eclipse.n4js.product/plugin.xml

Issue: https://github.com/eclipse/n4js/issues/291
The API Compare View extension had been associated with an Eclipse Activity (http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ui_activities.html) that we use to suppress unwanted plugin contributions in the IDE.

GH-291: Remove API Compare View from disabled contributions

---

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/PrevStateAwareDirtyStateManager.java

Issue: https://github.com/eclipse/n4js/issues/347
The existing implementation didn't allow for other subclasses of `DirtyStateEditorSupport`.
However, in case of manifest files the actual implementation was an instance of N4MFDirtyStateEditorSupport.
Since the method in use `getDirtyResource()` is part of the common superclass, this should fix the issue.

GH-347: Safer access to DirtyStateEditorSupport of dirty resources

---

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/ConditionalExpressionFactory.java

GH-402: Fix failing smoke tests on ConditionalExpression graph node creation

---

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/SanitizeImportsTransformation.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSValidator.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSImportValidator.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXReactBindingValidator.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend
tests/org.eclipse.n4js.n4jsx.xpect.ui.tests/manifest_no_react.n4mf
tests/org.eclipse.n4js.n4jsx.xpect.ui.tests/testdata/imports/NoReact.n4jsx.xt
tests/org.eclipse.n4js.n4jsx.xpect.ui.tests/testdata/imports/NoReactUnsused.n4jsx.xt

resolves #346 
This adds validation to N4JSX files, that will issue an error if `react` is not reachable from that module.
Validation issue will prevent file from being compiled when it is in invalid state.

GH-346: Graceful handling of missing "react" dependency for N4JSX

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/DestructureProcessor.xtend
tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_0395_CyclicReferencesInDestructuringPatterns.n4js.xt

GH-395: Cache miss exception for: var [a,b] = [0,b];

---

features/org.eclipse.n4js.dependencies.ui.sdk/feature.xml
features/org.eclipse.n4js.dependencies.ui.sdk/pom.xml
releng/org.eclipse.n4js.targetplatform/N4JS.setup
releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target

resolves #326 
Adds back junit runners integrations:
- Oomph worked locally
- maven builds passed, this time ;)
Note that jdt_runners integration might be re-worked / dropped with https://github.com/eclipse/Xpect/issues/224

GH-326d brings back runners required by the Xpect

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/NpmPackageToProjectAdapter.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/TypeDefinitionGitLocationProvider.java

Closes #435. Additionally, these related PRs change the N4JSD project structures so that they mirror the structure of the corresponding NPM packages:
*Related PRs*
- N4JSD: https://github.com/NumberFour/n4jsd/pull/10
- N4JSD Sandbox: https://github.com/NumberFour/n4jsd-sandbox/pull/4
**Attention**
Note the TODOs in `TypeDefinitionGitLocationProvider.java`: Before merging, reset the type definition branches to master!

GH-435: Wrong directory structure after NPM package adaptation

---

Jenkinsfile.new

resolves #438 
small adjustment to the `Jenkinsfile.new` to archive relevant binaries when branch is build

GH-438 adjust files archiving in new Jenkins

---

plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/N4HeadlessCompiler.java
plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/src/A.n4jsd
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample6_ExtendedSignature/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample6_ExtendedSignature/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample7_StaticPolyfills/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample7_StaticPolyfills/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/A.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/index.idx
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/X.adoc
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/index.idx

GH-466: Exported asciidoc output lacks an empty line in descriptions of class-jsdoc

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSExpressionValidator.xtend
tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/scoping/ErrorTest.xtend
tests/org.eclipse.n4js.n4idl.lang.tests/META-INF/MANIFEST.MF

Ticket: https://github.com/eclipse/n4js/issues/537
The change in the MANIFEST.MF is to prevent CI builds to completely fail.

GH-537: Add null-check for cast expression validation

---

plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/ArrowFunction.java
plugins/org.eclipse.n4js.model/model/N4JS.xcore
plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor_FunctionExpression.xtend
tests/org.eclipse.n4js.smoke.tests/src/org/eclipse/n4js/smoke/tests/GeneratedSmokeTestCases4.xtend

GH-616: Cache miss exception for (v) => v..foo()

---

plugins/org.eclipse.n4js.jsdoc/src/org/eclipse/n4js/jsdoc/JSDoc2HoverSerializer.java
plugins/org.eclipse.n4js.jsdoc/src/org/eclipse/n4js/jsdoc/JSDocCharScanner.java
plugins/org.eclipse.n4js.jsdoc/src/org/eclipse/n4js/jsdoc/MD2HTMLConvertingBuilder.java
plugins/org.eclipse.n4js.jsdoc/src/org/eclipse/n4js/jsdoc/N4JSDocletParser.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/N4JSHoverProvider.xtend
tests/org.eclipse.n4js.jsdoc.tests/.classpath
tests/org.eclipse.n4js.jsdoc.tests/.gitignore
tests/org.eclipse.n4js.jsdoc.tests/.project
tests/org.eclipse.n4js.jsdoc.tests/META-INF/MANIFEST.MF
tests/org.eclipse.n4js.jsdoc.tests/build.properties
tests/org.eclipse.n4js.jsdoc.tests/pom.xml
tests/org.eclipse.n4js.jsdoc.tests/src/org/eclipse/n4js/jsdoc/JSDoc2HoverSerializerTest.xtend
tests/org.eclipse.n4js.jsdoc.tests/src/org/eclipse/n4js/jsdoc/JSDocCharScannerTest.java
tests/org.eclipse.n4js.jsdoc.tests/src/org/eclipse/n4js/jsdoc/MD2HTMLConvertingBuilderTest.xtend
tests/org.eclipse.n4js.jsdoc.tests/xtend-gen/.gitignore

#658 
- added markdown to html converter (similar to a string builder) and JSDoc to hover html serializer
- adjusted hover provider to use JSDoc serializer, also added over support on declarations
- fixed minor problems in JSDoc parser/scanner

GH-658: Hover supports formatting of JSDoc including some markdown

---

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/handler/LibrariesFixHandler.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/dependencies/DependenciesCollectingUtil.java

resolves #691 
* adds graceful handling for unknown / broken projects during dependency calculation
* adds error dialog to notify user about issues (instead of terminating silently)

GH-691 Handle broken project / unknown projects in the dependency calculation

---

tests/org.eclipse.n4js.jsdoc2spec.tests/src/org/eclipse/n4js/jsdoc2spec/JSDoc2SpecProcessorFullTest.java

This test fails very often. Probably because of a newer GTK version.

CD-759: Ignore flaky test

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/GitCloneSupplier.java

Fixes https://github.com/eclipse/n4js/issues/743
A race condition could lead to a deletion of the type definitions repo on startup (see issue for a more thorough description).

GH-743: Declare synchronizeTypeDefinitions method as synchronized

---

builds/org.eclipse.n4js.product.build/N4JS__IDE.launch

Fixes https://github.com/eclipse/n4js/issues/771.
A previous misconfiguration of the included features lead to a validation issue of a dependency with regard to slf4j. This PR fixes this issue.

GH-771: Fix N4JS_IDE launch configuration

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ExternalIndexSynchronizer.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java

GH-874-fix: Library Manager unnecessarily uninstalls and then installs npms

---

Jenkinsfile.new
ci-master.jenkinsfile
docker-build/Dockerfile

resolves #891 
* adjusted docker to run as non-root
* bumps java `openjdk:8u151-jdk` -> `openjdk:8u171-jdk-stretch`
* bumps node version `8.11.1` -> `8.11.2`
* bumps docker label version `0.1.0` -> `0.1.3`
* adjusts node label `mesos-xlarge` -> `test-ec2-m5xlarge`

GH-891 As a smith I want to have a build image that can be run as non-root user.

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/NpmCLI.java

see #907
This PR fixes:
- bug of #907 
- re-build during NPM-install in case of transitive dependencies

GH-907: Library manager should install transitive dependencies without building in between

---

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/dependencies/ExternalLibrariesInstallHelper.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/dependencies/ProjectDependenciesHelper.java
tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/externalPackages/RunExternalLibrariesPluginTest.java

See #957.
Changes only in this repo.

GH-957: Fix issues when a workspace project depends on one of the published runtime NPMs

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/TypeDefinitionGitLocationProvider.java

See #809.
Corresponding PR in n4jsd repository has to be merged first:
https://github.com/NumberFour/n4jsd/pull/16

GH-809: use master branch for type definitions in n4jsd repository

---

plugins/org.eclipse.n4js.runner/src/org/eclipse/n4js/runner/RuntimeEnvironmentsHelper.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/dependencies/ExternalLibrariesInstallHelper.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/helper/SourceContainerAwareDependencyTraverser.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend

See #957.
Do not install shipped code project if "fake" version requested.

GH-957: Fix issues when a workspace project depends on one of the published runtime NPMs (part 2)

---

n4js-libs/packages/n4js-es5/package.json
n4js-libs/packages/n4js-node-mangelhaft/package.json
n4js-libs/packages/n4js-node/package.json
plugins/org.eclipse.n4js.runner/src/org/eclipse/n4js/runner/RunnerHelper.java

Issue: https://github.com/eclipse/n4js/issues/968
This PR adjusts the package.json files of the shipped n4js runtime environment projects to include the "src/" directories in the published version. Furthermore, the IDE runner was adjusted to not rely on the existence of source containers anymore, when computing the path of the execModule to be executed.

GH-968: NPE when running code in IDE with runtime code installed from npm

---

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/N4JSHoverProvider.xtend

Fixes GH-979
The fix is simply to add a missing `@Inject` annotation. I suspect this to be the outcome of a merge that did not go well.

GH-979: Documentation not shown when hovering mouse over elements

---

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/KeyUtils.java
plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/N4JSDReader.java
plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/RepoRelativePath.java
plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/SpecInfosByName.java
plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend
plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/RepoRelativePathHolder.java

#993 
Fixes:
- tests can be in other project then testee, use scoping to detect correct testee
- projects found in root of repository are handled correctly now
- if test case has no name, the number of the test case is used instead (otherwise html output would be broken)
Related:
- needs to be fixed in asciidoc macro srclnk: https://github.numberfour.eu/NumberFour/asciispec/issues/111

GH-993: asciidoc exporter now handles tests in other project than testee

---

docs/org.eclipse.n4js.spec/chapters/09_statements/statements.adoc
docs/org.eclipse.n4js.spec/chapters/12_components/components.adoc
docs/org.eclipse.n4js.spec/chapters/13_plainJS/plainJS.adoc
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/validation/SourceContainerAwareResourceValidator.java

Issue: https://github.com/eclipse/n4js/issues/809
This PR includes the last language spec update in the context of GH-809. I also renamed the`ManifestAwareResourceValidator` to `SourceContainerAwareResourceValidator`.

GH-809: Final spec update wrt. package.json files

---

plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/DependencyType.java
plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/ProjectDependency.java
plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/ProjectDescriptionPackage.java
plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/impl/ProjectDependencyImpl.java
plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/impl/ProjectDescriptionFactoryImpl.java
plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/impl/ProjectDescriptionPackageImpl.java
plugins/org.eclipse.n4js.model/model/ProjectDescription.xcore
plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/dependencies/DependenciesCollectingUtil.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/dependencies/DependencyInfo.java

Ticket: #821 
In this PR I made the following changes:
* I exposed the origin/type of a dependency (runtime, development or type as declared in the "dependencies", "devDependencies" and "typeDependencies" sections) in the ProjectDescription model via a new `DependencyType` enum type. Upon removal of type dependencies, this can be reduced to runtime and development.
* In the collection logic of the "big button", I filter the missing dependencies by their type (only collect non-type dependencies)
This PR is a preparation for merging the last subtask of #821, as it restores the backward compatibility of the introduced "typeDependencies". On the current master, the "big button" logic will attempt to install missing type dependencies. However, this fails since we do not publish type …

GH-821: Filter type dependencies in dependency collection of the "big button"

---

tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/typedefinitions/TypeDefinitionsShadowingPluginTest.java

Reverts eclipse/n4js#1037
Temporary roll-back. Changes will be re-applied soon.

Revert "GH-1036: Investigate recent failures of nightly builds"

---

plugins/org.eclipse.n4js.external.libraries/src/org/eclipse/n4js/external/libraries/ExternalLibrariesActivator.java
plugins/org.eclipse.n4js.external.libraries/src/org/eclipse/n4js/external/libraries/ExternalLibraryFolderUtils.xtend
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/ExternalLibrariesActionsHelper.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/preferences/external/ExternalLibraryPreferencePage.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/TargetPlatformInstallLocationProvider.java

This PR fixes a bug that was introduced by one of the subtasks of #821. 
On the current master, an invocation of the "big button" will delete the target definition `package.json` file but never re-create it. As a consequence, all following `npm install`-calls will output the following warnings:
```
npm WARN saveError ENOENT: no such file or directory, open '/.../workspace/.metadata/.plugins/org.eclipse.n4js.external.libraries/.n4npm/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/.../workspace/.metadata/.plugins/org.eclipse.n4js.external.libraries/.n4npm/package.json'
```
More importantly however, the external `node_modules` folder managed by the IDE, will no longer have a …

GH-821: Make sure target definition package.json is re-created properly

---

plugins/org.eclipse.n4js.runner/src/org/eclipse/n4js/runner/RunnerHelper.java
plugins/org.eclipse.n4js.ui/plugin.xml
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/project/N4JSNewProjectFileTemplates.xtend
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/project/N4JSNewProjectWizardCreationPage.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/project/N4JSProjectCreator.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/ui/dialogs/ExtensibleWizardNewProjectCreationPage.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionUtils.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/PackageJsonValidatorExtension.java

Ticket #1026 
With this PR, I have introduced support for scoped projects in the N4JS Project Wizard. The usage is as simple as using a project name like `@scope/project`.
@mor-n4 Please have a look.

GH-1026: Project wizard support for scoped projects

---

n4js-libs/packages/n4js-mangelhaft-cli/.project
n4js-libs/packages/n4js-mangelhaft-cli/package.json
n4js-libs/packages/n4js-mangelhaft-cli/tests/TestPrj/package.json
n4js-libs/packages/n4js-runtime-fetch/package.json
n4js-libs/packages/n4js-runtime-html5/package.json
n4js-libs/packages/n4js-runtime-n4-tests/package.json
n4js-libs/packages/n4js-runtime-node-tests/package.json
n4js-libs/packages/n4js-runtime-node/package.json
n4js-libs/packages/n4js.lang/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.assert.test/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.assert/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.console/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.ide.test/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.ide/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.xunit/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.runner.ide/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft.test/package.json
n4js-libs/packages/org.eclipse.n4js.mangelhaft/package.json

See #1018.
This fixes compilation problems in headless case in experienced some code bases.

GH-1018-sub3169: As a user I want the LibraryManager to use new n4jsd npms

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/CanLoadFromDescriptionHelper.java

We deactivate the "load from source" behavior for the time being, because it led to issues in an internal code base.

IDE-3180: deactivate load-from-source behavior in editors

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/conversion/AbstractN4JSStringValueConverter.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/conversion/IdentifierValueConverter.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/conversion/RegExLiteralConverter.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/conversion/ValueConverterUtils.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/ASTStructureValidator.xtend
tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/conversion/IdentifierValueConverterTest.java
tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/parser/templates/ParserTest.xtend

See #1120.
This PR fixes 2 bugs in the previous PR for this task, that were revealed by the ECMA test suite (which runs only in the nightly):
1. in identifiers (but not string literals, etc.) unknown escape sequences produce an error
2. the AST validation that shows an error if octal escape sequences are used in strict mode did not cover template string literals (only ordinary string literals). In the old code, template string literals had this handling in their value converter instead of the ASTStructureValidator.

GH-1120: Remove code indirectly copied from Java (part 2)

---

releng/utils/scripts/publish-n4js-libs.sh

Avoid duplicate version information in read-me files, caused by test publishing to local nexus before main publishing on same git checkout folder.

GH-1116: As a smith I want n4js-libs to be published with versions without a pre-release segment (minor fix)

---

plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/N4JSDataCollectors.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend

This removes an excessive invocation `IN4JSProject#exists()`.
See #1124.

GH-1124: As a smith I want to improve the build performance of external and user workspace (part 4)

---

releng/org.eclipse.n4js.parent/pom.xml

GH-1206: Maven build fails with Xtend compile errors since latest Eclipse release

---

plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/utils/TypeUtils.java
tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_1209_BogusErrorInN4idlWhenInvokingGenericMigrations.n4idl.xt

GH-1209: Bogus error messages in n4idl when invoking generic migrations

---

docker-build/Dockerfile
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/ExternalLibrariesActionsHelper.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/wizard/dependencies/RunnableInstallDependencies.java
plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/git/GitUtils.java
plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/io/FileCopier.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NodeJsBinary.java
releng/org.eclipse.n4js.parent/pom.xml
testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/builder/AbstractBuilderTest.java
testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/util/EclipseUIUtils.java
tests/pom.xml

See #1119.
This PR contains some minor adjustments of several utility methods used mainly by tests plus some related refactorings (e.g. moving some code from library manager into re-usable utility methods).
Also, the version of `node` and `yarn` used during Jenkins builds is increased.

GH-1119: As a smith I want to restructure the integration tests of N4JS

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ExternalLibraryWorkspace.java

GH-1262: Exception when opening same workspace after moving IDE executable to a new location

---

docs/org.eclipse.n4js.doc/src/faq/comparison-typescript.adoc

**TypeScript 3** added the `unknown` type, which behaves like **N4JS’s** `any` type.
See also https://github.com/Microsoft/TypeScript/issues/27265, which would add a compiler flag to **TypeScript** that would switch the implicit type from `any` to `unknown`.

docs(faq): Mention TypeScript 3’s `unknown` type

---

n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestAPI.n4js
n4js-libs/yarn.lock

GH-1317: n4js-mangelhaft should use "own" esm version as a fallback when executing tests

---

builds/org.eclipse.n4js.product.build/pom.xml
tests/org.eclipse.n4js.hlc.integrationtests/pom.xml

See #1335.
This PR contains various simplifications and clean ups beyond making the builds green.
In particular:
- make extended nightly truly independent from inhouse nightly
- remove siblingRepo and siblingMavenRepo
- remove stagingNpmRegistry and STAGING_NPM_REGISTRY
- use digest instead of tag to reference verdaccio docker image
- remove obsolete steps in some Jenkinsfiles
NOTE: most changes are contained in repository `n4js-n4`.

GH-1335: As a smith I want all nightly builds and deployment working with Java 11

---

inhouse-ci.jenkinsfile

Moves `inhouse-ci.jenkinsfile` back to repository `n4js`. See commit message for rationale.

GH-1361: As a smith I want to make builds simpler and more consistent (part 2)

---

docs/org.eclipse.n4js.ide.spec/chapters/02_views/views.adoc
tools/org.eclipse.n4js.hlc/src/org/eclipse/n4js/hlc/ProductLauncher.java

part two of https://github.com/eclipse/n4js/issues/1409
In order to get rid of the internal design document, this PR moves some remaining documentation from the internal design document to the public design document or to Java classes.

GH-1409: (Part 2) As a smith I need more design documentation publicly available

---

n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestRunner.n4js

See #1444.
Just a minor change in n4js-libs. This creates a (correct) error on branch `GH-1444` but not on master. Merging this ahead of time will simplify dealing with various tests, etc. on branch `GH-1444`.

GH-1444: As a smith I need to review the handling of Wildcards / ExistentialTypeRefs (aka capture conversion)

---

plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/JettyManager.java
tests/org.eclipse.n4js.tester.tests/pom.xml

Follow-up of GH-1453, since the actual problem was not solved before.
Turned out that on Eclipse Jenkins infrastructure, some defaults of Maven are different compared to enfore infrastructure (latter uses Docker). Namely, the maven-surefire plugin executes tests in parallel which caused races on hardware port 9415. Note that the race can be reproduced locally by setting the fork-count value to higher than one and setting the reuse-forks to true.
See Jenkins results of Eclipse of Branch GH-1453B here: https://ci.eclipse.org/n4js/job/GH-1453B/: The last five runs did not suffer anymore from the "could not bind" problem. Note that the one yellow build has a different problem.
Branch GH-1453C was introduced, since GH-1453B also contained lots of off-topic changes for testing reasons.

GH-1453C: Asynchronous Jetty Server shutdown causes problems on Eclipse Jenkins

---

testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/test/helper/hlc/N4jsLibsAccess.java

GH-1489: n4jsRuntimeLink may not be a symbolic link on Windows

---

jenkins/haw-pr.jenkinsfile

#1532
Side note: also use [ghef](https://www.npmjs.com/package/ghef) to filter events we can ignore on Jenkins (this does not change the repository)
Also disabled smoke tests since they caused problems... created #1533 for that.

GH-1532: moved jenkins to subfolder, disabled smoke tests

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/validation/N4JSIssue.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/GlobalUriResourceMap.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectStatePersister.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectUriResourceMap.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/UriResourceMap.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/WorkspaceAwareCanLoadFromDescriptionHelper.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/WorkspaceAwareResourceLocator.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/WorkspaceUriResourceMap.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XProjectManager.java
plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/n4idl/N4IDLVersionedImportsTransformation.java
plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ArrowFunction_Part2_Transformation.xtend
plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/DestructuringTransformation.xtend
plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/EnumAccessTransformation.xtend
plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/RestParameterTransformation.xtend
plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/SanitizeImportsTransformation.xtend
plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/AbstractTranspiler.java
plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/assistants/TypeAssistant.xtend
plugins/org.eclipse.n4js.ts.model/src/org/eclipse/n4js/ts/types/util/AllSuperTypeRefsCollector.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/helper/ImageDescriptionHelper.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/generator/AbstractSubGenerator.xtend
plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSCache.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/CanLoadFromDescriptionHelper.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/UserDataAwareScope.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSResourceValidator.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/helper/IssuesProvider.java
tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceLoadStatesTest.xtend

This PR ensures that resources are not loaded redundantly in the LSP builder case but
resolved from the dependent project's associated resource set instead. ResourceLocators to the rescue.
When a project is built initially, all its resources are loaded into a resource set including their AST. After the project build is done, the resource set is cleared.
Downstream projects in the dependency graph will attempt to use the resources from their dependencies. These are loaded from description into the resource set of their own project. Other projects may reuse these without the need to load them again. With the AST, the resources are very slim and can be kept in memory (for now).
Also the caching of validation issues was improved.
see #1561

GH-1561: Reduce memory footprint of LSP headless builder

---

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscCompiler.java
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/TestCatalogSupplier.java
plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/TestDiscoveryHelper.java
tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java

The catalog used to be computed based on an empty resource set without any index information attached. This was fixed to use the available index also in the headless case.
see #1561

GH-1561: Reduce memory consumption when creating the test catalog

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSOutputConfigurationProvider.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/validation/N4JSIssue.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectStateHolder.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectStatePersister.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectUriResourceMap.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ResourceChangeSet.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XProjectManager.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XBuildRequest.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java
testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/N4jscTestOptions.java
tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscBasicTest.java

When reading project state from disk that is no longer in sync with the file system, a proper incremental build must be triggered to ensure that transitively affected files are rebuilt.
Also we ensure that the build results are the same for the clean build and for the incremental build.
closes #1583

[#1583] Distinguish between deleted and modified resources on project load

---

plugins/org.eclipse.n4js.ts/src-env/env/builtin_js.n4ts
tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_1614_IncorrectSignatureOfArrayConcat.n4js.xt

GH-1614: Incorrect signature of built-in method Array#concat()

---

docs/org.eclipse.n4js.ide.spec/chapters/05_assistance/assistance.adoc
plugins/org.eclipse.n4js.jsdoc/src/org/eclipse/n4js/jsdoc/DocletParser.java
plugins/org.eclipse.n4js.jsdoc/src/org/eclipse/n4js/jsdoc/JSDocCharScanner.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/autoedit/AutoEditStrategyProvider.java
plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/autoedit/JSDocEditStrategy.java
tests/org.eclipse.n4js.jsdoc.tests/src/org/eclipse/n4js/jsdoc/tags/LineTagTest.java
tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc
tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/autoedit/AutoEditPluginUITest.xtend

#1496 
This PR adds the ability to automatically add prefilled comments with some JSDoc-tags when a comment for a method is created by pressing `ENTER` when the courser is at the inner position of a JSDoc-comment: `/**| */`
Currently only these tags are prefilled: `@param` `@return`
```
/**
* |
* @param a
* @param b
* @return
*/
public bar(a: String, b: boolean): A {return null}
```
---
`JSDocStrategy` extends the the `MultiLineTerminalsEditStrategy` by overriding the method `handleCursorInFirstLine` witch by default is extending multi line-comments.
Only if at the current position the next`(astElement instanceof N4MethodDeclaration)` in this PR the prefill-option is available, otherwise there will be created a default multi-line comment 
`/** */` -->
```
/**
*
*/
```

GH-1496: As a user I want JSDoc comments prefilled on creation

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XRequestManager.java
tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/xtext/XRequestManagerTest.xtend

See #1749.
I wonder if a `java.util.concurrent.CancellationException` can even occur at the two places I changed, but haven't removed the support for it, for now.

GH-1749: LSP builder not using Xtext API for handling cancellation exceptions

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/LspLogger.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java

See #1751.
First version using ordinary logging. Maybe a second version using a separate output channel will be provided as another PR later.
By the way:
I ran into an odd exception in the Guice injector that occurred only in the maven build, caused by `LspLogger`. Should be fixed by 8fce8c87af4d0f39f2b2fa700a4f4a9991bb1e72.
```
00:10:22.209  ERROR-1 (Unexpected error):  com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: 
com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: 
com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: 
com.google.inject.internal.util.$ComputationException: …
```

GH-1751: As a developer I want a super simple, preliminary progress indicator for the incremental build

---

plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/utils/TypeUtils.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch09_02_04__ImportStatements/Req136_DynamicImport.n4js.xt

See #1816.
This PR implements a minor, largely unrelated improvement done while looking into GH-1631. See GH-1816 for details.

GH-1816: Type references pointing to namespaces of dynamic imports are not flagged as dynamic

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/NodeModulesDiscoveryHelper.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java
tests/org.eclipse.n4js.cli.tests/PDTs/yarnDeepPackages2.pdt
tests/org.eclipse.n4js.cli.tests/PDTs/yarnDeepPackages3.pdt
tests/org.eclipse.n4js.cli.tests/PDTs/yarnSimple1b.pdt
tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/projectdiscovery/tests/CreateProjectStructureUtils.java

GH-1828: Yarn root project not found when setting the packages folder as the workspace of VSCode

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ResourceTaskContext.java

Lesson learned: relink is not properly implemented on XtextResource and
all of its subclasses.
closes #1830

GH-1830: Fixed regression in ResourceTaskContext wrt unloading

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ResourceTaskContext.java

GH-1842: Using method XtextResource#reparse() when refreshing resources causes exceptions

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/hover/N4JSElementSignatureProvider.xtend

GH-1858: "IllegalArgumentException: Unhandled parameter types" in N4JSElementSignatureProvider

---

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/LspLogger.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/util/ServerIncidentLogger.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java

Minor improvements of the functionality introduced with #1884:
1. include language version in name of folder where debug information is written to,
2. rename `DiagnosisLogger` to `ServerIncidentLogger`.
See #1884.

GH-1884: As a smith I want debug information to be written to a file whenever an error is logged

---

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSProjectBuilder.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ImmutableProjectState.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/packagejson/PackageJsonResourceDescriptionExtension.xtend

See #1932.
This is a second part with some additional, smaller fixes.
Unrelated to this, I also did a **performance check** of
* initial build from sources
* initial build from project files
using the OPR code base. In comparison to the VSCode extension in version 0.24.7 (about 7 weeks ago) there were no significant changes of build times.

GH-1932: As a developer I want that running 'yarn install' will solve all issues in a running LSP server (part 2)

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeJudgment.java
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_13_02__StringBasedEnums/Req41_NumberBasedEnums_Typing.n4js.xt

See #1946.
Fix: literals of number-based enums should also be a subtype of `int`, not just `number`.
(note: so far, `int` in N4JS is just a synonym for `number`)

GH-1946: As a developer I want number-based enums

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/ASTStructureValidator.xtend
tests/org.eclipse.n4js.tests.ecmatestsuite/res/blacklist_5.0.txt
tests/org.eclipse.n4js.tests.ecmatestsuite/res/blacklist_6.0.txt

Fixes failing tests in ecma test suite.
(did not show up in test builds, because that test suite isn't running in CI builds)

GH-1960: As a developer I want to use shorthand property names on object literals

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java
tests/org.eclipse.n4js.xpect.tests/model/typesystem/SimplifyUnionWithEmptyAnyArray.n4js.xt

GH-1968: || (logical or) and ?? (nullish coalescing) operators resolve different return types for the same objects

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java
tests/org.eclipse.n4js.xpect.tests/model/validation/controlflow/Instanceof_Guard_exclusion.n4js.xt

follow-up of #1992 
@mor-n4 noted a problem in the discussion started here: https://github.com/eclipse/n4js/pull/1993#discussion_r540105168
@mor-n4 elaborated that a solution can be (starting in line 633):
```js
boolean removeType = false;
for (TypeRef neverHoldingType : excludedTypes) {
if (ts.subtypeSucceeded(G, unionType, neverHoldingType)) {
removeType = true;
break;
}
}
if (!removeType) {
newUnionTypes.add(unionType);
}
```
This PR fixes the problem.

GH-1992B: Negated instanceof guards should strip their checked type from guarded IdentifierRefs

---

lsp-clients/n4js-vscode-extension/package.json

See #2014.
To test this:
1. Open a N4JS file in VSCode and make sure its editor is active.
2. Go to the "Run" tab.
3. If you do not yet have a `.vscode/launch.json` file, then click the link "create a launch.json file" in the "Run" tab (see [1]).
Otherwise, select "Add configuration ..." from the launch configuration drop-down menu (see [2]).
--> this should create and select a new N4JS launch configuration; review, adjust and save it!
4. Now go back the the open N4JS editor (make sure it has focus!).
5. Set a breakpoint somewhere.
6. Press F5 to launch/debug.
[1] creating a new `.vscode/launch.json` file:
[2] adding a new launch configuration to an existing `.vscode/launch.json` file:

GH-2014: Enable debugging of N4JS code in VS Code using the node debugger

---

releng/org.eclipse.n4js.parent/pom.xml

GH-2037: Fix unavailable maven repo fornax-platform.org/m2/repository

---

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/PatchedLauncherBuilder.java
plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/PatchedRemoteEndpoint.java
plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/codeActions/N4JSCodeActionService.java
tests/org.eclipse.n4js.json.tests/src/org/eclipse/n4js/json/tests/ide/contentassist/JSONCompletionTest.xtend

GH-2040: Fix output of cancelled request in Output View of VSCode 

---

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSExternalValidator.xtend
tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/ProjectWithoutGenerationBuilderTest.xtend
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_exportedFromN4jsd.n4jsd.xt
tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/project/NoValidationIdeTest.xtend
tests/org.eclipse.n4js.xpect.tests/xpect-tests/validation/IDE_657_external/UnallowedElements.n4jsd.xt
tests/org.eclipse.n4js.xpect.tests/xpect-tests/validation/IDE_784_external/ExtEnum.n4jsd.xt
tests/org.eclipse.n4js.xpect.tests/xpect-tests/validation/IDE_784_external/ExtFuns.n4jsd.xt

GH-2093: Bogus error shown when exporting a type alias from an N4JSD file

---

plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/utils/TypeUtils.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend
tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_validation_usedAsValue2.n4jsx.xt

See #2111.
This PR only includes some minor improvements of the handling of `IdentifierRef`s that point to type aliases. Since this is disallowed by a validation anyway, it does not have much impact, but improves consistency a bit and avoids some duplicate error messages. Also, might prove helpful in the future.
The actual topic of #2111 is not addressed by this PR.

GH-2111: As a developer I'd like to use type aliases as values (esp. in JSX tags) -- preparations

---

plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/ImmutableDataClass.java
testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/SystemOutRedirecter.java
testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractIdeTest.java

See #2128.
The actual integration test added in this user story is located in a separate repository because it uses a non-public N4JS code base as test data.

GH-2128: As a smith I want a performance test suite for content assist of n4js/d/x files

---

n4js-libs/package.json
n4js-libs/yarn.lock

GH-2151: Bump version of JS dependencies trim-newlines and normalize-url to avoid vulnerability alerts

---

lsp-clients/n4js-vscode-extension/package.json
lsp-clients/n4js-vscode-extension/src-gen/ExtensionProvider.js
n4js-tools/@n4js-temp/n4jsd-generator/package-lock.json
n4js-tools/@n4js-temp/n4jsd-generator/package.json

GH-2162: Bump versions of dependencies in VSCode extension and @n4js-tools/n4jsd-generator due to vulnerabilities

---

n4js-libs/package.json
n4js-libs/yarn.lock

GH-2198: Bump versions of dependencies in n4js-libs (@npmcli/git and path-parse) due to vulnerabilities

---

releng/utils/scripts/build-vscode-extension.sh

GH-2298: script for building the VS Code extension fails under latest version of macOS

---

n4js-libs/packages/n4js-cli/package.json
n4js-libs/yarn.lock
n4js-tools/n4jsd-generator/yarn.lock

GH-2330: Bump versions of dependencies in n4js-libs due to vulnerabilities

---

plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/IntersectionTypeExpression.java
plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/TypeRefsPackage.java
plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/IntersectionTypeExpressionImpl.java
plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefsPackageImpl.java
plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore
plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor_ObjectLiteral.xtend
tests/org.eclipse.n4js.spec.tests/xt-tests/polyprocessor_struc_obj_union_props.n4js.xt

GH-2462: Polyprocessor fails to confirm subtype relation in case of properties typed as union types that contain type ~Object with {}

---

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsModuleRefBuilder.java
plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/URIUtils.java
plugins/org.eclipse.n4js.xtext/src/org/eclipse/n4js/xtext/workspace/WorkspaceConfigSnapshot.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java
plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfigSnapshot.java

GH-2523: N4JS VSCode extension fails during start-up due to invalid path exception

---

lsp-clients/n4js-vscode-extension/webpack.config.cjs

GH-2525: VSCode extension fails to start due to wrong static value for variable import.meta.url

---

testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtFileRunner.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/AbstractXtParentRunnerTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/BeforeAfterInvocationTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/DefinitionTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/ElementKeywordTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/IgnoreWrongRunnerTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/IssueConfigurationTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/ModifiersTest.java
tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/SuppressedIssuesTest.java

This PR replaces calls to `fireTestRunStarted/Finished` by `fireTestSuiteStarted/Finished` in `XtFileRunner`. According to the [JUnit 4 docs](https://github.com/junit-team/junit4/blob/16228f3ccea3c6f1170488e0e268f3601d130f75/src/main/java/org/junit/runner/notification/RunNotifier.java#L87), `fireTestRunStarted/Finished` are not supposed to be invoked by custom runners, which should use `fireTestSuiteStarted/Finished` instead.

Replace fireTestRunStarted/Finished by fireTestSuiteStarted/Finished in XtFileRunner
