eclipse/n4js

releng/org.eclipse.n4js.targetplatform/N4JS.setup
* adjusted branding
* adjusted git clone task
=> #14 adjust Oomph setup to use eclipse/n4js git repo

Jenkinsfile
adding configuration for maven calls to avoid issue #48
=> #48 add workspace property to maven calls

docs/org.eclipse.n4js.doc/about.html, docs/org.eclipse.n4js.spec/about.html, plugins/org.eclipse.n4js.environments/about.html, plugins/org.eclipse.n4js.external.libraries/about.html, plugins/org.eclipse.n4js.ui/about.html, plugins/org.eclipse.n4js.xpect/about.html, plugins/org.eclipse.n4js/about.html_TEMPLATE, releng/org.eclipse.n4js.releng.utils/about.html, testhelpers/org.eclipse.n4js.tester.tests.helper/META-INF/MANIFEST.MF, testhelpers/org.eclipse.n4js.tester.tests.helper/about.html, testhelpers/org.eclipse.n4js.tester.tests.helper/build.properties, testhelpers/org.eclipse.n4js.ui.tests.helper/about.html, tests/org.eclipse.n4js.tests.ecmatestsuite/about.html, tools/org.eclipse.n4js.hlc/about.html
=> #50: updated about.html files, added third-party information

.gitattributes
Adds syntax highlighting to the n4js files.
=> #90: add syntax highlighting

tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/AT_IDEBUG_654_ExportPlainJsModulesTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/AT_IDEBUG_654_MissingPolyfillImportsTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/AT_IDEBUG_695_CannotSetFinalFieldInCtorForStaticPolyfillsTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/IncompleteApiImplementationTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalMainModuleTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithDefinitionFilesTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithSingleFileCompileTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithSingleProjectCompileTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/N4jscArgumentOrderTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/N4jscBasicTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/TargetPlatformConfigurationsTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/TargetPlatformRangeConfigurationsTest.java, tests/org.eclipse.n4js.hlc.tests/src/test/java/org/eclipse/n4js/hlc/tests/jar/SingleFileCompileN4jscJarTest.java
=> #119: Don't run n4jsc with --debug flag in tests

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/ComposedMemberScope.java
This PR fixes a bug in the bug fix of PR #123.
=> #95: Cache miss exception for composed members

releng/org.eclipse.n4js.targetplatform/N4JS.setup
=> #133: As a smith I don't need the Eclipse Setup Tasks to clean-build the whole project

tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/array/array_constructor.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_freeze.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_isExtensible.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_seal.n4js.xt, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalMainModuleTest.java, tests/org.eclipse.n4js.spec.examples.xpect.tests/testdata/spec_chap_07_01_04/Ex63_Array_Literal.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/importexport/IDEBUG_684/AT_IDEBUG_684_NamespacesOptimized_NoUnusedNamespace_CommonJS.n4js.xt
Task: https://github.com/eclipse/n4js/issues/173
=> GH-173: Fix failing output tests due to changed behavior of newer NodeJS

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/workingsets/GitRepositoryAwareWorkingSetManager.java
Issue: NumberFour/n4js#414
The issue always appeared if some of the workspace projects were contained in Git Repositories that were not listed in the Git Repositories View. So to reproduce, it should suffice to launch a workspace where the projects were imported without adding their repos in the Repository View. After a restart the refresh issues would start. This is fixed now.
For builds see internal PR.
=> GHOLD-414: Fix refresh behavior of N4JS Git Working Sets

plugins/org.eclipse.n4js.generator.common/src/org/eclipse/n4js/generator/common/AbstractSubGenerator.xtend, plugins/org.eclipse.n4js.generator.common/src/org/eclipse/n4js/generator/common/IGeneratorMarkerSupport.java, plugins/org.eclipse.n4js.generator.ui/src/org/eclipse/n4js/generator/ui/GeneratorMarkerSupport.java, plugins/org.eclipse.n4js.n4jsx/src/org/eclipse/n4js/n4jsx/validation/N4JSXValidator.xtend, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/labeling/helper/ImageDescriptionHelper.xtend, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/validation/ManifestAwareResourceValidator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTMetaInfoCache.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/AbstractPolyProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/AbstractProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ArrowFunctionProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeDeferredProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSCache.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSPostProcessor.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/PostProcessingAwareResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/CustomInternalTypeSystem.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/RuleEnvironmentExtensions.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeComputer.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeSystemHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/InferenceContext.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/AbstractMessageAdjustingN4JSValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/AbstractN4JSDeclarativeValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSResourceValidator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/helper/IssuesProvider.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/validation/AutomaticCancelationTest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/dirtystate/CanLoadFromDescriptionPluginUITest.xtend, tests/org.eclipse.n4js.xsemantics.tests/src/org/eclipse/n4js/typesystem/AbstractInferenceContextTest.xtend
=> #150: Check handling of cancel indicator in type resolution

plugins/org.eclipse.n4js.n4jsx/src/org/eclipse/n4js/n4jsx/helpers/ReactHelper.xtend, plugins/org.eclipse.n4js.n4jsx/src/org/eclipse/n4js/n4jsx/typesystem/N4JSXUnsupportedExpressionTypeHelper.xtend
Link: https://github.com/eclipse/n4js/issues/209
=> GH-209: Occationally, looking up react definitions fails in JSX

plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/BreakStatement.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/ContinueStatement.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/LabelRef.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/N4JSPackage.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/impl/ContinueStatementImpl.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/impl/LabelRefImpl.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/impl/N4JSPackageImpl.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/util/N4JSAdapterFactory.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/util/N4JSSwitch.java, plugins/org.eclipse.n4js.model/model/N4JS.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSLinker.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/ASTStructureValidator.xtend
fixes #214
AC 2. from the task description will be done as part of #208
=> #214: ASTStructureValidator must not resolve proxies

plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NodeBinariesConstants.java, tests/org.eclipse.n4js.runner.ui.tests/META-INF/MANIFEST.MF, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/tests/NodeVersionTest.java, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/tests/package-info.java, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/ui/tests/NodeVersionUITest.java, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/ui/tests/RunnerHelperPluginUITest.xtend, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/ui/tests/RuntimeEnvironmentResolutionPluginUITest.xtend, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/ui/tests/ShippedCodeRunConfigurationPluginUITest.java, tests/org.eclipse.n4js.runner.ui.tests/src/org/eclipse/n4js/runner/ui/tests/TestDiscoveryHelperPluginUITest.xtend
#204 
- updated node.js to version 8 and npm to version 5
- added test checking the correct version (for error recovery)
=> #204: updated node/npm version and added test

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/PostProcessingAwareResource.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/postprocessing/PostProcessingTriggerTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/scoping/ComposedMemberCachingTest.xtend
=> #208: Post-processing not triggered when resolving proxies without type inference

plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/types/TModule.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/types/TypesPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/types/impl/TModuleImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/types/impl/TypesPackageImpl.java, plugins/org.eclipse.n4js.ts.model/model/Types.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/AbstractN4JSCore.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/IN4JSCore.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResourceDescriptionStrategy.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/UserdataMapper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/ASTStructureValidator.xtend, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/AbstractN4JSTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceLoadStatesTest.n4js, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceLoadStatesTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/scoping/N4JSScopingTestWithIndexTest.xtend
=> #228: As a smith I want to add some minor refinements related to AST reconciliation

plugins/org.eclipse.n4js.n4jsx.ui/src/org/eclipse/n4js/n4jsx/ui/N4JSXUiModule.xtend, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/search/N4JSEditorResourceAccess.java
== Task
Link: https://github.com/eclipse/n4js/issues/234
=> GH-234: NPE in find references 

plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeProcessor.xtend
=> #240: fix typing in resources that were forced to be loaded from source

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/ThirdPartyValidator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch09_02_01__Let/Let_SpecialCases.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Others/ThirdParty_Babel_LetConstInFunctionExpression.n4js.xt
=> #247: n4jsc compilation failure if function name & variable name are same

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/LocallyKnownTypesScopingHelper.xtend
=> 251: NullPointerException in scoping

plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/PostProcessingAwareResource.java
Some more documentation and some minor refactoring.
See #240.
=> #240: Exception in editor during type inference in a dependency that was loaded from source (part 2)

tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/TargetPlatformRangeConfigurationsTest.java
=> #255: Fix test TargetPlatformRangeConfigurationsTest

plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/UtilN4.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTMetaInfoCache.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSPostProcessor.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/PostProcessingAwareResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSResourceValidator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/validation/AvoidFollowUpExceptionsInValidationTest.xtend
See commit message for more info.
See also #232.
=> #232: improve error handling in case of exceptions during post-processing

n4js-libs/packages/n4js-runtime-fetch/src/n4js/Headers.n4jsd, n4js-libs/packages/n4js-runtime-fetch/src/n4js/Request.n4jsd, n4js-libs/packages/n4js-runtime-fetch/src/n4js/Response.n4jsd, n4js-libs/packages/n4js-runtime-fetch/src/n4js/URL.n4jsd, n4js-libs/packages/n4js-runtime-fetch/src/n4js/fetch/RequestInit.n4jsd, n4js-libs/packages/n4js-runtime-node/src/n4js/http.n4jsd, n4js-libs/packages/n4js-runtime-node/src/n4js/stream.n4jsd, n4js-libs/packages/n4js-runtime-node/src/n4js/url.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-fetch/src/n4js/Headers.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-fetch/src/n4js/Request.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-fetch/src/n4js/Response.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-fetch/src/n4js/URL.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-fetch/src/n4js/fetch/RequestInit.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-node/src/n4js/http.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-node/src/n4js/stream.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-node/src/n4js/url.n4jsd
=> #257 - Fix minor runtime library definitions

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSFunctionDefinitionTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSMethodTypesBuilder.xtend
=> #267: Avoid early proxy resolution in types builder

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/N4JSDocument.java
=> #265:  Changed strategy to unblock hover and hyperlinks

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java
=> #281: IndexOutOfBoundsException in N4JSResource

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/CFEChildren.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/StandardCFEFactory.java, tests/org.eclipse.n4js.flowgraphs.tests/model/Destructuring.n4js.xt
In https://github.com/eclipse/n4js/pull/289, an error was overlooked and is fixed in this PR. The error is related to the optimisation algorithms.
=> GH-235fix: Fixes for failing tests due to PR-289. Test added.

plugins/org.eclipse.n4js.n4jsx.ui/src/org/eclipse/n4js/n4jsx/ui/N4JSXUiModule.xtend, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java
=> #265: make reconciliation indicator (tiny clock) available in N4JSX

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/CFEFactoryDispatcher.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/DebuggerStatementFactory.java, tests/org.eclipse.n4js.flowgraphs.tests/model/OtherStatements.n4js.xt
=> GH-296: Exception when building control flow graph

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/AbstractCaseClauseFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/ControlFlowGraphFactory.java
=> Fix failing smoke tests due to flowgraph optimization

tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/bugs/AbstractPluginUITest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/bugs/SelectAllProjectExplorer_PluginUITest.java
=> #319: Fix randomly failing UI test SelectAllProjectExplorer_PluginUITest, method testWorkingSetAndProject

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSClusteringBuilderConfiguration.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/N4JSDirtyStateEditorSupport.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/PrevStateAwareDirtyStateManager.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/PrevStateAwareDocumentBasedDirtyResource.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/EcoreUtilN4.java
=> IDE-2888: Improved detection of unnecessary editor reconcilation

plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/VariableDeclaration.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/impl/VariableDeclarationImpl.java, plugins/org.eclipse.n4js.model/model/N4JS.xcore, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_0254_ConstInDestructOverlooked.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_01_Array_and_Object_Destructuring/destructuring/Destruct_const.n4js.xt
=> #254: Violating const in destructured variables not caught by n4js compiler but does result in a runtime error

plugins/org.eclipse.n4js.generator.common/src/org/eclipse/n4js/generator/common/AbstractSubGenerator.xtend
=> #335: NullPointerException in AbstractSubGenerator#doGenerate()

tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/APIReplacementN4jscJarTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/AbstractN4jscJarTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/N4jscJarTestersTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/SingleFileCompileN4jscJarTest.java, tools/scripts/mvn-cp-n4jsjar.sh
Link: https://github.com/eclipse/n4js/issues/360
Only script added. No build needed.
=> GH-360: Add script that executes mvn and copy n4jsc.jar

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceTest.xtend
=> #362: N4JSResource#loadFromDescription() should not change state of resource in case of failure

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/ControlFlowEdge.java
=> #359: Fix regression in org.eclipse.n4js.xsemantics.caching.PerformanceSubtypeTest.testSubtyping1000

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/FGUtils.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/N4JSFlowAnalyzer.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/ControlFlowGraphFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/FlowGraph.java, tests/org.eclipse.n4js.flowgraphs.tests/model/ControlFlowContainers.n4js.xt
=> GH-378: Control flow engine needs to support ExpressionAnnotationList in broken AST

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/ExternalLibrariesReloadHelper.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/preferences/external/ExternalLibraryPreferencePage.java
Note: since the exception is nearly impossible to reproduce, we should only merge this if the changes also make sense on their own, without considering the ConcurrentModificationException.
=> GH-373: Fix random Concurrent Modification exception

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java
Task: https://github.com/eclipse/n4js/issues/374
=> Fix random OutOfMemory when building internal test project

plugins/org.eclipse.n4js/src/org/eclipse/n4js/n4jsx/ReactHelper.xtend
=> fix NPE in react helper

plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTMetaInfoUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/lang/tests/cache/GH197NullComputedName.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceLoadStatesTest.xtend
Task: https://github.com/eclipse/n4js/issues/404
=> GH-404: Update N4JS Resource Load States table in design doc with AST meta cache column

plugins/org.eclipse.n4js.n4mf.ui/src/org/eclipse/n4js/n4mf/ui/N4MFEditor.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSEditor.java
Task: https://github.com/eclipse/n4js/issues/412
=> GH-412: Shortcut for synchronizing text editor and file in project explorer

plugins/org.eclipse.n4js.n4mf.ui/src/org/eclipse/n4js/n4mf/ui/N4MFEditor.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSEditor.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/utils/ImportUtil.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/ProjectUtils.xtend, tests/org.eclipse.n4js.xpect.ui.tests/testdata/scoping/GH_420_importsMainModule/express/manifest.n4mf, tests/org.eclipse.n4js.xpect.ui.tests/testdata/scoping/GH_420_importsMainModule/express/src/index.n4jsd, tests/org.eclipse.n4js.xpect.ui.tests/testdata/scoping/GH_420_importsMainModule/manifest.n4mf, tests/org.eclipse.n4js.xpect.ui.tests/testdata/scoping/GH_420_importsMainModule/src/index.n4jsd.xt
Task: https://github.com/eclipse/n4js/issues/420
=> GH-420: Problem with using module name index.n4jsd in an N4JSD project when having dependency with another N4JSD project

plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/n4jsx/transpiler/utils/JSXBackendHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/n4jsx/ReactHelper.xtend
Task: https://github.com/eclipse/n4js/issues/426
=> GH-426: Severe transpiler problem when n4jsd project is in workspace

plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/n4jsx/transpiler/utils/JSXBackendHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java
=> GH-433: Exception in JSXBackendHelper in case project "react" exists in workspace

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/1000_a.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/1001_b.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/test/ReqTest.n4js, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/1000_a.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/1001_b.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/X.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/index.idx
=> GH-442: As a developer I want the layout of generated Requirement ADOC files to be adjusted

testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/builder/AbstractBuilderTest.java
=> GH-444: Randomly failing test case in class InstallUninstallNPMPluginUITest

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/1000_a.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/1001_b.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/1000_a.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/1001_b.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/test/ReqTest.n4js
=> GH-454: Layout problem in generated adoc files

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/1000_a.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/1001_b.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample5_LinkToReqIDs/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/1000_a.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample8_NoTodoForReqIDs/expectedADoc/1001_b.adoc
=> GH-454b: Layout problem in generated adoc files (Refactoring)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/InferenceContext.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/Reducer.java, tests/org.eclipse.n4js.xpect.tests/model/typesystem/polyExpressions/DefinitionSiteVarianceHandlingConstraintSolver.n4js.xt, tests/org.eclipse.n4js.xsemantics.tests/src/org/eclipse/n4js/typesystem/InferenceContextTest.xtend
See #460.
1. Return to original solution of PR #463.
2. Improve a heuristic in `InferenceContext` to obtain "nicer" results.
=> GH-460: As a smith I want to add support for definition site variance in constraint solver (PART 2)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/NpmPackageToProjectAdapter.java
=> GH-472 adjust type definitions logging

plugins/org.eclipse.n4js/src/org/eclipse/n4js/misc/DestructureHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor.xtend, tests/org.eclipse.n4js.xpect.tests/model/typesystem/polyExpressions/DefinitionSiteVarianceHandlingConstraintSolver.n4js.xt
Task: https://github.com/eclipse/n4js/issues/479
=> GH-479: Regression in Type inference on destructuring literals

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/NpmPackageToProjectAdapter.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/LightweightException.java
=> GH-489 handle missing main module in less verbose manner

plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/N4JSModel.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/N4JSProjectSourceContainer.java
=> GH-504 check if location segments are valid

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/InferredElements.java
=> GH-510 check for null

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScopingHelper.xtend
=> GH-518 handle null in MemberScopingHelper

plugins/org.eclipse.n4js.model/src/org/eclipse/n4js/n4JS/N4JSASTUtils.java, plugins/org.eclipse.n4js.ts/src-env/env/builtin_n4.n4ts, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/TypeProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScopingHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSEnumValidator.java, tests/org.eclipse.n4js.n4ide.spec.tests/xpect-test/Ch05_01_01_03__CA_Complete_Identifier_Reference/ContentAssist_StringBasedEnums.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_13_02__StringBasedEnums/Req41_StringBasedEnums_Typing.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_13_02__StringBasedEnums/Req41_StringBasedEnums_Usage.n4js.xt
=> GH-485: No validation for accessing reflection information on StringBased enums (which have no runtime reflection info)

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ModuleWrappingTransformation.xtend, tests/org.eclipse.n4js.hlc.tests/probands/external_imports/external.project/manifest.n4mf, tests/org.eclipse.n4js.hlc.tests/probands/external_imports/external.project/src/Main.n4js, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalImportsTest.java
=> GH-526 fixed compilation of imports with the same module name

plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/TestDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ResourceNameComputer.xtend, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscTestersTest.java, tests/org.eclipse.n4js.tester.tests/src/org/eclipse/n4js/tester/tests/discovery/HeadlessTestDiscoveryTest.java
=> GH-530 TestCatalog: move output folder info from origin to fqn

Jenkinsfile, Jenkinsfile.new
=> GH-533: Automatically start multibranch builds only for branch "master"

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResourceDescriptionStrategy.java
=> GH-539: Suspicious argument of a private method in class N4JSResourceDescriptionStrategy

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/symbols/SymbolFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/BinaryLogicalExpressionFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/StandardCFEFactory.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/findReferences/ConcreteSyntaxAwareReferenceFinder.java
=> NPE in SymbolFactory when running smoke tests

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/SpecTestInfo.java, plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/src/A.n4jsd, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/test/ATests.n4js, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample7_StaticPolyfills/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample7_StaticPolyfills/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/X.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/index.idx
=> GH-617: Jsdoc2spec generates @Final twice

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/utils/UIUtils.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/bugs/AbstractPluginUITest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/bugs/SelectAllProjectExplorer_PluginUITest.java
See #620.
This contains a refactoring required for https://github.numberfour.eu/NumberFour/n4js-n4/pull/304.
=> GH-620: Fix problem in AssignWorkingSetsSwtBotTest

n4js-libs/packages/n4js-runtime-fetch/src/n4js/Headers.n4jsd, n4js-libs/packages/n4js-runtime-node/src/n4js/Buffer.n4jsd, n4js-libs/packages/n4js-runtime-node/src/n4js/url.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-fetch/src/n4js/Headers.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-node/src/n4js/Buffer.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-node/src/n4js/url.n4jsd
=> GH-614: adding Headers.forEach, Buffer.from, NodeURL.query

tests/org.eclipse.n4js.hlc.tests/pom.xml
=> GH-626 cleanup org.eclipse.n4js.hlc.tests/pom.xml

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample10_TodoTags/src/A.n4jsd, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample2/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample3_RedundantLines/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample4_TesteeForFunctions/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample6_ExtendedSignature/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample6_ExtendedSignature/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample7_StaticPolyfills/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample7_StaticPolyfills/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/X.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/xpect-tests/adoc/Comparable.n4jsd.xt, tests/org.eclipse.n4js.jsdoc2spec.tests/xpect-tests/adoc/IDE-2456.n4jsd.xt, tests/org.eclipse.n4js.jsdoc2spec.tests/xpect-tests/adoc/SimpleFunction.n4jsd.xt, tests/org.eclipse.n4js.jsdoc2spec.tests/xpect-tests/adoc/SimpleType.n4jsd.xt
=> GH-624: Jsdoc2Spec generates some TODO blocks inconsistently

features/org.eclipse.n4js.dependencies.ui.sdk/feature.xml, releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
Task: https://github.com/eclipse/Xpect/issues/224
This PR removes the JDT runner hack.
=> GH-224-Xpect: Remove JDT runner hack

docs/org.eclipse.n4js.spec/chapters/05_classifiers/classifiers-part-02-members.adoc, docs/org.eclipse.n4js.spec/chapters/05_classifiers/classifiers-part-03-structural.adoc
=> GH-593: Spec ctor not initializing inherited fields (specification update)

plugins/org.eclipse.n4js.external.libraries.update/src/org/eclipse/n4js/external/libraries/update/UpdateShippedCode.java, plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/N4jscJarUtils.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_GHOLD_212_transpilecrashTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_532_transpilecrashTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_542_missing_dep_to_project_under_testTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_654_ExportPlainJsModulesTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_654_MissingPolyfillImportsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_695_CannotSetFinalFieldInCtorForStaticPolyfillsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/IncompleteApiImplementationTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalImportsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalMainModuleTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithDefinitionFilesTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithSingleFileCompileTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithSingleProjectCompileTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4JSXTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscArgumentOrderTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscBasicErrorTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscBasicTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscDependentProjectDependenciesTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscTestersTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/TargetPlatformConfigurationsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/TargetPlatformRangeConfigurationsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/APIReplacementN4jscJarTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/N4jscJarTestersTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/SingleFileCompileN4jscJarTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/n4idl/ObsoleteVersionedImportsTest.xtend, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java
=> GH-655 align names of the build type and test flags in N4JSC

plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/N4JSDReader.java, plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/ADocSerializer.xtend, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/A.adoc, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample1/src/A.n4jsd, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/index.idx, tests/org.eclipse.n4js.jsdoc2spec.tests/testresourcesADoc/SpecSample9_StaticPolyfill/expectedADoc/poly1.X.adoc
=> GH-664: Jsdoc2Spec generates @Final twice and randomly fails on some tests

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/SingleFileCompileN4jscJarTest.java
resolves #685 
This gracefully handles exception in the resource loading.
Further changes to the external libraries are curently developed in branch #653
=> GH-685 handle exception in post processing

tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallFromManifestCompileRunN4jscExternalImportsTest.java, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/DependenciesHelper.java
=> GH-689 fix NPE in N4JSC when build type is "projects"

tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/DependenciesHelper.java
=> NPE in N4JSC when srcFiles is not provided

n4js-libs/packages/org.eclipse.n4js.mangelhaft.assert.test/test/n4js/org/eclipse/n4js/mangelhaft/types/DispatchQueueTest.n4js, n4js-libs/packages/org.eclipse.n4js.mangelhaft/src/n4js/org/eclipse/n4js/mangelhaft/types/DispatchQueue.n4js
=> GH-697: DispatchQueue doesn't call listeners with correct call context

plugins/org.eclipse.n4js.runner.nodejs.ui/src/org/eclipse/n4js/runner/nodejs/ui/launch/NodejsLaunchConfigurationTab.xtend, plugins/org.eclipse.n4js.runner.nodejs/src/org/eclipse/n4js/runner/nodejs/NodeRunOptions.java, plugins/org.eclipse.n4js.runner.nodejs/src/org/eclipse/n4js/runner/nodejs/NodeRunner.java, plugins/org.eclipse.n4js.runner.ui/src/org/eclipse/n4js/runner/ui/AbstractLaunchConfigurationMainTab.java, plugins/org.eclipse.n4js.runner.ui/src/org/eclipse/n4js/runner/ui/RunnerLaunchConfigurationMainTab.java, plugins/org.eclipse.n4js.runner/src/org/eclipse/n4js/runner/RunConfiguration.java, plugins/org.eclipse.n4js.tester.ui/src/org/eclipse/n4js/tester/ui/AbstractTesterLaunchShortcut.java
#716 
- added new configuration setting for environment variables
- configuration settings are copied from project config, if present.
=> #716: added environment vars to node.js launch, copy from project launch

docker-build/Dockerfile
Signed-off-by: Gunnar Bastkowski <gunnar.bastkowski@enfore.com>
=> Upgrade yarn in Dockerfile

n4js-libs/packages/n4js-node/manifest.n4mf, n4js-libs/packages/n4js-node/package.json, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-node/manifest.n4mf, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-node/package.json
=> use fixed versions in manifest

n4js-libs/packages/org.eclipse.n4js.mangelhaft.test/test/n4js/org/eclipse/n4js/mangelhaft/test/TestExecutorAsyncOrderTest.n4js
=> GH-731: adding test cases for mangelhaft issue

tests/org.eclipse.n4js.hlc.tests/probands/external_with_n4jsd/project.using.external.from.n4js/src/Main.n4js, tests/org.eclipse.n4js.hlc.tests/probands/external_with_n4jsd/project.using.external.from.n4jsx/src/MainX.n4jsx, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithDefinitionFilesTest.java
=> adjust test stability

plugins/org.eclipse.n4js.smith/src/org/eclipse/n4js/smith/DataCollectors.java
=> add locking to data collectors

tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscBasicTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/SingleFileCompileN4jscJarTest.java, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/ErrorExitCode.java, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java
Task: https://github.com/eclipse/n4js/issues/794
=> Catch the case when the last argument passed to n4jsc.jar is not a valid list of files

plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/N4jscJarUtils.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_GHOLD_212_transpilecrashTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_532_transpilecrashTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_542_missing_dep_to_project_under_testTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_654_ExportPlainJsModulesTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_654_MissingPolyfillImportsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/AT_IDEBUG_695_CannotSetFinalFieldInCtorForStaticPolyfillsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/IncompleteApiImplementationTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalImportsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalMainModuleTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithDefinitionFilesTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithSingleFileCompileTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallCompileRunN4jscExternalWithSingleProjectCompileTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/InstallFromManifestCompileRunN4jscExternalImportsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscBasicErrorTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscBasicTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscDependentProjectDependenciesTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscDuplicateProjectsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/N4jscTestersTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/TargetPlatformConfigurationsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/TargetPlatformRangeConfigurationsTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/N4jscJarTestersTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/SingleFileCompileN4jscJarTest.java, tests/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/n4idl/ObsoleteVersionedImportsTest.xtend
=> remove debug verbose flags from tests

n4js-libs/packages/n4js-runtime-esnext/src/n4js/Object.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-esnext/src/n4js/Object.n4jsd
=> GH-826: Provide support for ES2015 Object.setPrototypeOf, ES2017 Object.values, ES2017 Object.entries

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/quickfix/N4JSQuickfixProvider.xtend
=> GH-745: Quick Fix for "node_modules folder and N4JS index are out of sync" does not handle cancellation correctly (InterruptedException)

plugins/org.eclipse.n4js.n4mf/src/org/eclipse/n4js/n4mf/validation/N4MFValidator.xtend, plugins/org.eclipse.n4js.n4mf/src/org/eclipse/n4js/n4mf/validation/messages.properties, tests/org.eclipse.n4js.n4mf.xpect.tests/model/validation/duplicates/test1.n4mf.xt, tests/org.eclipse.n4js.n4mf.xpect.tests/model/validation/mainModule/negative/mainModuleNegative.n4mf.xt
=> GH-828: Split error messages in manifest file regarding missing module specifier

docs/org.eclipse.n4js.doc/assets/headers/articles/docinfo-footer.html, docs/org.eclipse.n4js.doc/assets/headers/faq/docinfo-footer.html, docs/org.eclipse.n4js.doc/assets/headers/features/docinfo-footer.html, docs/org.eclipse.n4js.doc/assets/headers/releases/docinfo-footer.html, docs/org.eclipse.n4js.doc/assets/headers/releases/docinfo.html, docs/org.eclipse.n4js.doc/assets/headers/userguides/docinfo-footer.html
=> GH-837 adjust web page of the project to comply with GDPR

plugins/org.eclipse.n4js.jsdoc/emf-gen/org/eclipse/n4js/jsdoc/dom/DomPackage.java, plugins/org.eclipse.n4js.jsdoc/emf-gen/org/eclipse/n4js/jsdoc/dom/impl/DomPackageImpl.java, plugins/org.eclipse.n4js.json.model/emf-gen/org/eclipse/n4js/json/JSON/JSONPackage.java, plugins/org.eclipse.n4js.json.model/emf-gen/org/eclipse/n4js/json/JSON/impl/JSONPackageImpl.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/N4JSPackage.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/impl/N4JSPackageImpl.java, plugins/org.eclipse.n4js.n4mf.model/emf-gen/org/eclipse/n4js/n4mf/N4mfPackage.java, plugins/org.eclipse.n4js.n4mf.model/emf-gen/org/eclipse/n4js/n4mf/impl/N4mfPackageImpl.java, plugins/org.eclipse.n4js.transpiler/emf-gen/org/eclipse/n4js/transpiler/im/ImPackage.java, plugins/org.eclipse.n4js.transpiler/emf-gen/org/eclipse/n4js/transpiler/im/impl/ImPackageImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/TypeRefsPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefsPackageImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/types/TypesPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/types/impl/TypesPackageImpl.java, plugins/org.eclipse.n4js.utils/emf-gen/org/eclipse/n4js/utils/validation/ValidationPackage.java, plugins/org.eclipse.n4js.utils/emf-gen/org/eclipse/n4js/utils/validation/impl/ValidationPackageImpl.java
=> GH-841: Insert copyright headers into generated code

features/org.eclipse.n4js.json.sdk/feature.xml
=> GH-851: Add copyright and license information to JSON feature.xml

Jenkinsfile.new, ci-master.jenkinsfile
=> disable GTK3 to workaround UI allocation warnings

plugins/org.eclipse.n4js.n4mf/src/org/eclipse/n4js/n4mf/resource/ManifestMerger.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ExternalIndexSynchronizer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java
see #848 
Also added a check to avoid modifications of a broken manifest.
=> GH-848: 'Install npm package to workspace' does not work for broken external library projects (only on second try)

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java
=> GH-866: Most quickfixes cannot be applied in the errors view

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/EclipseExternalLibraryWorkspace.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ExternalLibraryWorkspace.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/HlcExternalLibraryWorkspace.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java
=> GH-862: Library Manager does not install types for transitive dependencies

plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/Version.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java
=> GH-874: Library Manager unnecessarily uninstalls and then installs npms

n4js-libs/packages/n4js-runtime-esnext/src/n4js/String.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-esnext/src/n4js/String.n4jsd
=> GH-879: Add String.padStart, String.padEnd definitions

Jenkinsfile.new, releng/org.eclipse.n4js.parent/pom.xml, tests/pom.xml
resolves https://github.com/eclipse/n4js/issues/881
updates used plugins
=> GH-881 update used plugins

tests/pom.xml
=> Reactivate ECMA test suite

tests/pom.xml
=> Reactivate ECMA test suite (Part 2)

Jenkinsfile.new, ci-master.jenkinsfile
=> As a smith I want to run maven in quiet mode

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSExpressionValidator.xtend
=> add instanceof check

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-910 update link to missing update site

builds/org.eclipse.n4js.product.build/N4JS__IDE.launch, builds/org.eclipse.n4js.product.build/org.eclipse.n4js.product.product, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/building/N4JSMarkerUpdater.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/containers/N4JSAllContainersState.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/workingsets/ManualAssociationAwareWorkingSetManager.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/workingsets/WorkingSetManagerStartup.java
=> GH-917: IllegalStateException: Workbench has not been created yet.

inhouse-ci.jenkinsfile, releng/org.eclipse.n4js.parent/pom.xml
=> fix failsafe plugin version

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> update update site link

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-938 update webtools update site link

releng/org.eclipse.n4js.parent/pom.xml
=> workaround for xtend dependency

n4js-libs/packages/n4js-cli/npm-build.sh, publish-n4js-libs-npm.sh
Task: https://github.com/eclipse/n4js/issues/952
=> Make n4js-cli's build script work uniformly for both publishing and integration test

n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestAPI.n4js, n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestRunner.n4js, n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.xunit/src/n4js/org/eclipse/n4js/mangelhaft/reporter/xunit/XUnitReporter.n4js
=> GH-961: Using sync variants of readFile and writeFile

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/internal/EclipseBasedN4JSWorkspace.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/helper/SoureContainerAwareDependencyTraverser.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend
See #956.
No changes in N4 repo.
=> GH-956: InvocationTargetException when installing missing dependencies in OPR ("big button")

tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/externalPackages/InstallRuntimeFromNpmPluginTest.java
=> GH-968: delete npm projects from library manager after test completion

n4js-libs/packages/n4js-runtime-es2015/src/n4js/Array.n4jsd, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-es5/package.json, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-node-mangelhaft/package.json, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-node/package.json, plugins/org.eclipse.n4js.external.libraries/shipped-code/runtime/n4js-runtime-es2015/src/n4js/Array.n4jsd
resolves #995 
(added as starting point, if adjustments are needed, e.g. for tests, pls take care)
=> add missing method to the array polyfill

plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/BuildSetComputer.java, plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/HeadlessHelper.java, plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/N4HeadlessCompiler.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/FileBasedWorkspace.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/PolyFilledProvision.java, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/HeadlessCompilerFactory.java, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/xpect/projects/AutoDiscoveryFileBasedWorkspace.java, tests/org.eclipse.n4js.accesscontrol.tests/src/org/eclipse/n4js/accesscontrol/tests/AccessControlTest.java, tests/org.eclipse.n4js.generator.headless.tests/src/org/eclipse/n4js/generator/headless/tests/ScenarioTest.java, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java
Minor clean-up regarding package.json merge.
Ticket: https://github.com/eclipse/n4js/issues/809
=> GH-809: package.json cleanup in headless compiler + validation

plugins/org.eclipse.n4js.smith/src/org/eclipse/n4js/smith/TimedDataCollector.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/building/WriteNewResourceDescriptionsImplementation.java
=> GH-1012: NPE and AIOOB exception when using performance view

docker-build/Dockerfile, n4js-libs/lerna.json, n4js-libs/npm-publish-canary.sh, n4js-libs/package.json, plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft/src-gen/org/eclipse/n4js/mangelhaft/TestExecutor.js, plugins/org.eclipse.n4js.external.libraries/shipped-code/mangelhaft/org.eclipse.n4js.mangelhaft/src/n4js/org/eclipse/n4js/mangelhaft/TestExecutor.n4js
Task: https://github.com/eclipse/n4js/issues/1054
=> #1054: Global latest lerna version is used for publishing and not the fixed version specified in package.json

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java
=> GH-1055: IDE fails to setup type definitions for external dependencies

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/preferences/external/InstallNpmDependencyDialog.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java
=> GH-957: Fix issues when a workspace project depends on one of the published runtime NPMs (part 2)

inhouse-ci.jenkinsfile
Task: https://github.com/eclipse/n4js/issues/1061
In this PR, I cleanup the workspace after the build in the jenkinsfile.
=> Cleanup workspace in Jenkins pipeline

n4js-libs/packages/n4js-runtime-esnext/package.json, n4js-libs/packages/n4js-runtime-esnext/src/n4js/TypedArray.n4jsd, n4js-libs/packages/n4js-runtime-html5/package.json, n4js-libs/packages/n4js-runtime-html5/src/n4js/TextDecoder.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/TextEncoder.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Window.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/base64.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/webcrypto.n4jsd
This PR contains type definitions for
- atob / btoa (base64 support)
- TextEncoder / TextDecoder
- TypedArrays
- web crypto (see https://developer.mozilla.org/en-US/docs/Web/API/Crypto)
=> GH-1066: Add required type definitions for web cryptography support.

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/EclipseExternalIndexSynchronizer.java
=> GH-1070: Fix corner case when requested npm package was installed to a nested node_modules folder but not to the top level node_modules folder

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ExternalIndexSynchronizer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ShadowingInfoHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend, tests/org.eclipse.n4js.ui.tests/probands/ShadowingCreatesVersionWarnings/P1/_project, tests/org.eclipse.n4js.ui.tests/probands/ShadowingCreatesVersionWarnings/P1/package.json, tests/org.eclipse.n4js.ui.tests/probands/ShadowingCreatesVersionWarnings/P1/src/Client.n4js, tests/org.eclipse.n4js.ui.tests/probands/ShadowingCreatesVersionWarnings/n4js.lang/_project, tests/org.eclipse.n4js.ui.tests/probands/ShadowingCreatesVersionWarnings/n4js.lang/package.json, tests/org.eclipse.n4js.ui.tests/probands/ShadowingCreatesVersionWarnings/n4js.lang/src/Lang.n4js, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/externalPackages/ShadowingCreatesVersionWarningsPluginTest.java
=> GH-1075: As a user, I don't always need version checking with shadowed projects

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/internal/EclipseBasedN4JSWorkspace.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/internal/N4JSEclipseModel.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/internal/N4JSEclipseProject.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/URIUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/N4JSModel.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionLoader.java
=> GH-1080: IllegalArgumentException: Path for project must have only one segment.

n4js-libs/packages/n4js-runtime-es2015/src/n4js/Array.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/webcrypto.n4jsd, n4js-libs/packages/n4js-runtime-n4-tests/test/n4js/runtime/n4/TestPromisifiable.n4js, n4js-libs/packages/n4js-runtime-node-tests/test/n4js/es-module-tests/ex10/A.n4js, n4js-libs/packages/n4js-runtime-node-tests/test/n4js/es-module-tests/ex10/run.n4js
Closes #1078.
See corresponding PRs: 
- https://github.numberfour.eu/NumberFour/onlinepresence/pull/2107 - merged
- https://github.numberfour.eu/NumberFour/stdlib_n4js/pull/463
- https://github.numberfour.eu/NumberFour/stdlib_api/pull/294
**DO NOT MERGE THIS BEFORE THE CORRESPONDING PRs ARE MERGED!**
=> GH-1078: Fix some runtime type definitions 

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/EclipseExternalIndexSynchronizer.java
=> GH-1085: Fix index synchronizer issues wrt. shadowed projects

n4js-libs/packages/n4js-es5/src/js/rt/post-systemjs.js, n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestAPI.n4js, n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestCLI.n4js, n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestRunner.n4js, n4js-libs/packages/n4js-node-mangelhaft/src/js/n4js-mangelhaft-cli.js, n4js-libs/packages/n4js-node/src/js/rt/node-cjs-loader-polyfill.js, n4js-libs/packages/n4js-node/src/js/run.js
=> GH-1107: Loader mode for API not impl, don't set by default, exit code improvements

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/AbstractJSONValidatorExtension.java, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/api-impl/missing-implemented-projects/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/empty-strings/library-project/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/empty-strings/library-project2/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/main-module/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/module-filter-n4js-matches/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/module-filters/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/@/MyProject/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/@_invalidScope/MyProject/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/@invalid*scope/Invalid*Project/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/@invalid*scope/MyProject/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/@myScope/Invalid*Project/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/@myScope/MyProject/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/npmScopes/MyProject/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/plainjs/warningsDefaultPlainjs/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/plainjs/warningsExplicitPlainjs/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/project-name/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/structure/sources-section/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.ui.tests/xpect/conflicting-polyfills/client/package.json.xt
=> GH-1123: Trailing dot in pre-release tags of semver version constraints cause validation errors

plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/NpmCLI.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/TargetPlatformInstallLocationProvider.java, testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/builder/ExternalLibrariesSetupHelper.java
=> GH-1121: Fix failing test due to error related with npm installation using the sandbox

plugins/org.eclipse.n4js.ts.ui/src/org/eclipse/n4js/ts/ui/navigation/URIBasedStorageEditorInputFactory.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java, tests/org.eclipse.n4js.ui.tests/probands/Hyperlink/Hyperlink/_project, tests/org.eclipse.n4js.ui.tests/probands/Hyperlink/Hyperlink/package.json, tests/org.eclipse.n4js.ui.tests/probands/Hyperlink/Hyperlink/src/ABC.n4js, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/hyperlink/HyperlinkPluginTest.java
=> GH-1122: Jump to definition and searching for inherited fields does not work in external libraries

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/building/N4JSMarkerUpdater.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageHelper.java
=> GH-1124: As a smith I want to improve the build performance of external and user workspace (part 1)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSExpressionValidator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch06_03_01_TypeCast/CastThis.n4js.xt
=> #1104: Missing validation for invalid cast between unrelated types involving this

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSAnnotationValidator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_02_02_01__StructuralThisTypeInCtorAndSpecParameter/Req59_2_NoMultipleSpecParameters.n4js.xt
=> #1008: `@Spec` annotation allowed on non-constructors

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSTypeValidator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch08_01_05_ObjectLiteral/ObjectLiteral_SuperfluousProperties_Nested.n4js.xt
=> #942: Missing warning while assigning arrays of structural types

n4js-libs/packages/n4js-node/src/js/run.js
=> GH-1161: Use max signed 32bit int for timer value

plugins/org.eclipse.n4js.smith/src/org/eclipse/n4js/smith/TimedDataCollector.java
See #1163.
This is just a quick fix. It will render some performance diagrams useless (those that rely on the individual data points). Either a better solution of the memory leak should be implemented or those diagrams should be removed.
Since this is only functionality for internal testing/debugging, the priority is low and this quick fix is sufficient, for now.
=> GH-1163: TimedDataCollector causing memory issues

docs/org.eclipse.n4js.spec/chapters/16_jsx/jsx.adoc, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSGlobals.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend, tests/org.eclipse.n4js.n4jsx.spec.ui.tests/xpectTests/Req241118_JSXElements_Referring_to_XML_Elements.n4jsx.xt
=> GH-1146: n4jsx emits warnings for svg elements

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/proposals/imports/ImportsAwareReferenceProposalCreator.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/proposals/imports/N4JSReplacementTextApplier.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/collections/Arrays2.java, plugins/org.eclipse.n4js.xpect.ui/src/org/eclipse/n4js/xpect/ui/methods/contentassist/ContentAssistXpectMethod.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/PlainAccessOfAliasedImportDescription.java, tests/org.eclipse.n4js.n4ide.spec.tests/xpect-test/Ch05_01_01_03__CA_Complete_Identifier_Reference/GH1138_ContentAssistNotUsingExistingAlias.n4js.xt, tests/org.eclipse.n4js.xpect.ui.tests/testdata_nonvalidating/proposal/contentassist/AT_1035__14_5_2_3__ContentAssist_Multiline_Expectations_dotted_notation.n4js.xt, tests/org.eclipse.n4js.xpect.ui.tests/testdata_nonvalidating/proposal/contentassist/AT_1035__14_5_5__ContentAssist_apply_multiline.n4js.xt
=> GH-1183: Content assist not using alias in case of existing imports

tests/org.eclipse.n4js.hlc.integrationtests/pom.xml, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/APIReplacementN4jscJarTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/AbstractN4jscJarTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/CompileRunTestAllPassN4jscJarTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/CompileRunTestWithFailuresN4jscJarTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/HlcTestingConstants.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/N4jsCliTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/PerformanceReportN4jscJarTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/SingleFileCompileN4jscJarTest.java, tests/org.eclipse.n4js.hlc.integrationtests/src/org/eclipse/n4js/hlc/integrationtests/TesterN4jscJarTest.java, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java
=> GH-1188: Some tests not executed in maven build

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/containers/N4JSStorage2UriMapper.java
See #1190.
See my comment here: https://github.com/eclipse/n4js/issues/1190#issuecomment-445810533
=> GH-1190: NullPointerException when running the Setup External Libraries Wizard

plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/scoping/TypesScopeFilter.xtend, tests/org.eclipse.n4js.ts.xpect.tests/model/scoping/scopes.n4ts.xt
See #926.
This PR adds a minor fix to avoid some incorrect proposals during content assist.
=> GH-926: As a user I want content assist to be faster and better sorted

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/internal/N4JSEclipseModel.java
=> GH-1194: "Install missing dependencies" gets confused by non-N4JS projects in workspace

plugins/org.eclipse.n4js.ts.ui/src/org/eclipse/n4js/ts/ui/navigation/BuiltinSchemeUriMapperContribution.java, plugins/org.eclipse.n4js.ts.ui/src/org/eclipse/n4js/ts/ui/navigation/IURIBasedStorage.java, plugins/org.eclipse.n4js.ts.ui/src/org/eclipse/n4js/ts/ui/navigation/URIBasedStorage.java, plugins/org.eclipse.n4js.ts.ui/src/org/eclipse/n4js/ts/ui/navigation/URIBasedStorageEditorInputFactory.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/navigator/internal/N4JSResourceLinkHelper.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/navigator/internal/ResourceNode.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/utils/UIUtils.java, releng/org.eclipse.n4js.targetplatform/n4js.dict, testhelpers/org.eclipse.n4js.ui.tests.helper/META-INF/MANIFEST.MF, testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/builder/AbstractBuilderParticipantTest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/hyperlink/HyperlinkPluginUITest.java
=> GH-1199: Jump to definition / hyperlink not working in external libraries when opening file from Project Explorer

docker-build/Dockerfile, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/regexp/regexp_exec.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/regexp/regexp_lastIndex.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/string/string_match.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/ChB_N4Objects/N4Inspection.n4js, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/di/compiledMetaInfo/01_DiMetaSimple.n4js.xt, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/bugs/GHOLD_45_CheckIgnoreAnnotationAtClassLevel_PluginUITest.java
=> GH-1215: As a smith I want to make tests in N4JS repo compatible with latest node/yarn version

plugins/org.eclipse.n4js.external.libraries/src/org/eclipse/n4js/external/libraries/ExternalLibrariesActivator.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/building/N4JSGenerateImmediatelyBuilderState.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/containers/N4JSStorage2UriMapper.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/ExternalProjectMappings.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/internal/EclipseBasedN4JSWorkspace.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/ExternalLibraryWorkspace.java
see #1154 
contains some fixes to support several node_modules folders (specified by the user).
=> GH-1154: As a developer I want the IDE to use my custom node_modules folder

docker-build/Dockerfile, plugins/org.eclipse.n4js.external.libraries.update/src/org/eclipse/n4js/external/libraries/update/UpdateShippedCode.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/binaries/BinariesPreferencePage.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/BinariesProvider.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/LibraryManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/external/NpmCLI.java, tools/org.eclipse.n4js.hlc.base/src/org/eclipse/n4js/hlc/base/N4jscBase.java
=> GH-1252: Revisit error messages in case npm/yarn is not installed after recent changes to the library manager

docs/org.eclipse.n4js.spec/chapters/12_components/components.adoc, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/ProjectDescription.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/ProjectDescriptionPackage.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/impl/ProjectDescriptionImpl.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/projectDescription/impl/ProjectDescriptionPackageImpl.java, plugins/org.eclipse.n4js.model/model/ProjectDescription.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java
=> GH-1253: Improve user experience if yarn workspace root folder is imported as Eclipse project

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_1257_InvalidStaticPolyfillOfBuiltInType.n4js.xt
=> GH-1257: Invalid static polyfill of built-in type leads to uncaught exception in type system

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/ImportedElementsScopingHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/AbstractMemberScope.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScope.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScopeRequest.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScopingHelper.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_09__TypeModifiers/DynamicTypes_vs_StaticField.n4js.xt
=> GH-1260: Validation does not respect dynamically accessed members that are also defined as static members

plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/utils/TypeUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/InferenceContext.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/ThisTypeComputer.xtend, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_1273_IncorrectBoundThisTypeRefInGenericClasses.n4js.xt, tests/org.eclipse.n4js.xsemantics.tests/src/org/eclipse/n4js/typesystem/InferenceContextTest.xtend
=> GH-1273: Incorrect BoundThisTypeRef for this-keyword in generic classes

n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestAPI.n4js
=> GH-1285: exclude n4js-node and mangelhaft tool 

docker-build/Dockerfile, eclipse-nightly.jenkinsfile, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/BinariesConstants.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/BinariesLocatorHelper.java
Task: https://github.com/eclipse/n4js/issues/1288
Build: https://ci.eclipse.org/n4js/job/nightly/154/console
=> GH-1288: As a smith I want to fix the Eclipse nightly build (missing yarn)

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/ExternalProjectMappings.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/URIUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/preferences/ExternalLibraryPreferenceStoreImpl.java, testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/util/ProjectTestsUtils.java, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/_project, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/package.json, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/@myScope/Lib/_project, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/@myScope/Lib/package.json, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/@myScope/Lib/src/C.n4js, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/Lib/_project, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/Lib/package.json, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/Lib/src/C.n4js, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/XClient/_project, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/XClient/package.json, tests/org.eclipse.n4js.ui.tests/probands/YarnWorkspaceExample/YarnWorkspaceProject/packages/XClient/src/ClientModule.n4js, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/externalPackages/SideBySideYarnWorkspacePluginTest.xtend
=> GH-1303: As a user I want to use a yarn workspace by importing only some of its contained packages into the IDE

docs/org.eclipse.n4js.spec/chapters/11_extFeatures/extFeatures.adoc, n4js-libs/packages/n4js-runtime-es2015/src/n4js/Function.n4jsd, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSClassValidator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Constraints128_Applying_Polyfills/package.json, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Constraints128_Applying_Polyfills_Builtin/package.json, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Constraints128_Applying_Polyfills_Generics/package.json, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Req152_Polyfill/package.json, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Req152_Polyfill/src/Req152_PolyfillClassModifiers.n4jsd.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Req152_Polyfill/src/Req152_PolyfillClassSameName.n4jsd.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Req152_Polyfill/src/Req152_PolyfillConstructor.n4jsd.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_04_Polyfill_Definitions/Req152_Polyfill/src/Req152_PolyfillNoConsumesOrImplements.n4jsd.xt, tests/org.eclipse.n4js.xpect.ui.tests/testdata/polyfill/GH_1312_PolyfillForFinalClass/package.json, tests/org.eclipse.n4js.xpect.ui.tests/testdata/polyfill/GH_1312_PolyfillForFinalClass/src/C.n4jsd.xt, tests/org.eclipse.n4js.xpect.ui.tests/testdata/polyfill_static/GH_1312_PolyfillForFinalClass/package.json, tests/org.eclipse.n4js.xpect.ui.tests/testdata/polyfill_static/GH_1312_PolyfillForFinalClass/src/C.n4js, tests/org.eclipse.n4js.xpect.ui.tests/testdata/polyfill_static/GH_1312_PolyfillForFinalClass/src_filler/C.n4js.xt
#1312
@mor-n4 please; could be merged once the compiler either allows polyfills on final classes or the builtin final is removed.
=> GH-1312: As a developer I want to have access to the propery 'name' of functions

releng/org.eclipse.n4js.targetplatform/N4JS.setup
=> GH-1331: As a smith I want to have editors for Jenkins and Docker files

docker-build/Dockerfile, n4js-libs/lerna.json, n4js-libs/package.json, n4js-libs/yarn.lock, releng/utils/scripts/publish-n4js-libs.sh
=> GH-1341: Fix "Internal Server Error" in Jenkins during publishing of n4js-libs

n4js-libs/packages/n4js-runtime-html5/src/n4js/CSPDirective.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Element.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/EventTarget.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/MediaQueryList.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Navigator.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Screen.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/ScreenOrientation.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/ScreenOrientationType.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Window.n4jsd
=> GH-1339: Corrections and additions for runtime-html5

docker-build/Dockerfile, eclipse-nightly.jenkinsfile, inhouse-ci.jenkinsfile, releng/org.eclipse.n4js.parent/pom.xml, releng/utils/scripts/publish-n4js-libs.sh, tests/org.eclipse.n4js.hlc.integrationtests/pom.xml
=> GH-1335: As a smith I want all nightly builds and deployment working with Java 11

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-1359: As a smith I need a new version of Xpect fixing the Java 9 system class loader issue

plugins/org.eclipse.n4js/src/org/eclipse/n4js/n4JS/extensions/SourceElementExtensions.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/N4JSScopeProvider.xtend
=> GH-1355: Scoping of to polyfillee and polyfilled types not consistent

tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/N4JSResourceTest.xtend
=> GH-1375: Test in N4JSResourceTest failing when run locally

plugins/org.eclipse.n4js.model/model/N4JS.xcore
[#1373] More explicit type information as a workaround for Xcore bug
=> [#1373] More explicit type information as a workaround for Xcore bug

docs/org.eclipse.n4js.spec/n4jsspec.bib, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/ExistentialTypeRef.java, plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore
#1418, replacement of #932 by @katrinleinweber
Applied changes proposed by @katrinleinweber and did some additional bib cleanup.
@katrinleinweber Thank you very much for your support. Since we have these weird IP-validation problems and I did not want to bother you more than necessary, I re-applied you changes here. Please have a look -- if this is ok with you, let us know. I cannot assign you as a reviewer since you are not committer. Please simply let us know via a comment in this PR.
=> Hyperlink DOIs against preferred resolver

n4js-libs/packages/n4js-cli/npm-postinstall.js, n4js-libs/packages/n4js-cli/package.json
=> Fix npm install failure on Windows

n4js-libs/packages/n4js-runtime-html5/src/n4js/MessageChannel.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/MessageEvent.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/MessagePort.n4jsd
=> GH-1434: Adding MessageChannel, MessagePort, MessageEvent

n4js-libs/package.json, n4js-libs/packages/n4js-cli/package.json, n4js-libs/yarn.lock
=> GH-1430: Upgrade deps

plugins/org.eclipse.n4js.generator.headless/src/org/eclipse/n4js/generator/headless/ConfiguredGeneratorFactory.java
=> GH-1436: Headless builder failing with exception depending on current working directory

plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/BinariesConstants.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/BinariesValidator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NpmrcBinary.java
=> GH-1447: On windows the binaries for node or yarn are sometimes not found

plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/Binary.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NodeJsBinary.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NpmBinary.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/NpmrcBinary.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/binaries/nodejs/YarnBinary.java
=> GH-1449: On windows case-insensitive environment variables names are not respected 

plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/N4JSProjectSourceContainer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/locations/SafeURI.java
=> GH-1443: On Windows some imports cannot be resolved

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/ControlFlowGraphFactory.java, plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/server/JettyManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java
=> GH-1453: Asynchronous Jetty Server shutdown causes problems on Eclipse Jenkins

plugins/org.eclipse.n4js.ui/plugin.xml
=> GH-1387 Dialog 'Open Resource' (Shift+CMD+R) broken when focus on editor

eclipse-nightly.jenkinsfile, n4js-libs/packages/n4js-cli/README.md
=> GH-1464: As a user I want to have a download link for n4jsc.jar on the Eclipse page

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/AbstractEdge.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/ControlFlowEdge.java, tests/org.eclipse.n4js.flowgraphs.tests/model/TryAndThrowStatements.n4js.xt
=> GH-1474: Error when building control flow graph in try/finally with exception and return statements

docs/org.eclipse.n4js.design/chapters/03_releng/releng.adoc, plugins/org.eclipse.n4js.runner/src/org/eclipse/n4js/runner/RunConfiguration.java, releng/org.eclipse.n4js.parent/pom.xml, releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-1480: As a smith I want to update the N4JS IDE to Eclipse 2019-09

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/CoalesceExpressionFactory.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/UnsupportedFeatureValidator.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/parser/CoalesceExpressionTest.xtend
Unfortunately yesterday's push did not succeed, so the review feedback is here.
=> GH-1494: Incorporated review feedback

n4js-libs/packages/n4js-runtime-html5/src/n4js/GeoLocation.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Navigator.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/ServiceWorker.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/ServiceWorkerContainer.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/ServiceWorkerRegistration.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Worker.n4jsd
=> GH-1522: HTML5 service worker API defs

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/external/ProjectStateChangeListener.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/n4idl/migrations/MigrationMatcher.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4IDLMigrationValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSTypeValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/externalPackages/IndexSynchronizerPluginTest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/hyperlink/HyperlinkPluginUITest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/misc/ClearCacheOnCleanPluginUITest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/project/NpmScopesPluginTest.xtend
Some clean up provided by @szarnekow.
=> some clean up provided by szarnekow

plugins/org.eclipse.n4js.transpiler/emf-gen/org/eclipse/n4js/transpiler/im/ImPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/FunctionTypeExpression.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/TypeRef.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/TypeRefsPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/UnknownTypeRef.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/FunctionTypeExpressionImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefsPackageImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/UnknownTypeRefImpl.java, plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubstTypeVariablesJudgment.java, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_1527_EMFThrowsExceptionDueToNullInEList.n4js.xt
=> GH-1527: EMF throws exception due to null being added to an EList

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XIncrementalBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XSource2GeneratedMapping.java
[#1538] Fixed regressions in LSP builder
=> [#1538] Fixed regressions in LSP builder

docs/org.eclipse.n4js.design/chapters/03_releng/releng.adoc, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/symbols/SymbolFactory.java, releng/org.eclipse.n4js.parent/pom.xml, releng/org.eclipse.n4js.releng.utils/src/org/eclipse/n4js/filechecker/AbstractFileChecker.java, releng/org.eclipse.n4js.releng.utils/src/org/eclipse/n4js/filechecker/FileChecker.java, releng/org.eclipse.n4js.releng.utils/src/org/eclipse/n4js/filechecker/Report.java, releng/org.eclipse.n4js.releng.utils/src/org/eclipse/n4js/filechecker/ReportUtils.java, releng/org.eclipse.n4js.targetplatform/N4JS.setup, testhelpers/org.eclipse.n4js.ui.tests.helper/src/org/eclipse/n4js/tests/util/ProjectTestsUtils.java
=> GH-1550: Minor clean up related to migration of third-party repository n4js-n4 to n4js-extended

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscCompiler.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XWorkspaceManager.java
[#1567] Prettier duration output
=> [#1567] Prettier duration output

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscMain.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/validation/N4JSDiagnosticConverter.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/IssueAcceptor.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java
=> GH-1566: Fix build issue reproducable on OPR b69cf632f

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscOptions.java
=> GH-1563: As a developer I want the CLI not to be confused by Locales other than 'en'

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XTopologicalSorter.java
=> GH-1578: Make build order deterministic (LSP)

n4js-libs/packages/n4js-cli/bin/n4jsc.js, n4js-libs/packages/n4js-cli/src/n4js/index.n4js
=> GH-1589: Set heap defaults unless defined per JAVA_TOOL_OPTIONS

n4js-libs/.gitignore, n4js-libs/packages/n4js-mangelhaft-cli/package.json, n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestAPI.n4js, n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestCLI.n4js, n4js-libs/packages/n4js-mangelhaft-cli/tests/npm-test.sh, n4js-libs/yarn.lock
=> GH-1603: Eval workspace setting for emitProjectTestCatalogs

plugins/org.eclipse.n4js.ide/META-INF/MANIFEST.MF, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSWorkspaceManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/validation/N4JSIssue.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XWorkspaceManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XAbstractRequest.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XCancellable.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XReadRequest.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XRequestCancelIndicator.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XRequestManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XWriteRequest.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/findReferences/XWorkspaceResourceAccess.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/N4JSUiModule.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSRuntimeModule.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSLocationInFileProvider.xtend, tests/org.eclipse.n4js.ide.tests/META-INF/MANIFEST.MF, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/xtext/XRequestManagerTest.xtend
=> [#1599] Forked server.concurrent from Xtext

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscLanguageClient.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ParallelBuildManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectUriResourceMap.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/WorkspaceUriResourceMap.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XProjectManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XWorkspaceManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/generator/SubGeneratorRegistry.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/AbstractN4JSCore.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/CanLoadFromDescriptionHelper.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/CliCompileResult.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/GeneratedJSFilesCounter.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/N4jscTestLanguageClient.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/N4jscBasicTest.java
Necessary fixes to the ParallelBuildManager after recent changes in the LSP impl.
see #1552
=> [#1552] Small adjustments to parallel project builder

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/analysers/NullDereferenceAnalyser.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/analysers/NullDereferenceFailed.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/analysers/NullDereferenceResult.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/Assumption.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/PartialResult.java, tests/org.eclipse.n4js.xpect.tests/model/validation/dataflow/NullUndefined_May_OptionalChaining.n4js.xt
=> GH-1617: Create warnings for variables with values of optional chained expressions

testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/Project.xtend, tests/org.eclipse.n4js.accesscontrol.tests/src/org/eclipse/n4js/accesscontrol/tests/AccessControlTest.java, tests/org.eclipse.n4js.accesscontrol.tests/src/org/eclipse/n4js/accesscontrol/tests/ScenarioGenerator.java
Adjust access control tests to recent changes of CliTools merged with PR #1630.
=> GH-1629: Minor improvements and clean up required for changes in integration tests

n4js-libs/packages/n4js-cli/src/n4js/n4jsc.n4js, plugins/org.eclipse.n4js.ts/src-env/env/builtin_js.n4ts
=> GH-1642: Fix n4js-cli to identify Java version more robust

lsp-clients/n4js-vscode-extension/package.json, lsp-clients/n4js-vscode-extension/syntaxes/n4js.tmLanguage.json, lsp-clients/n4js-vscode-extension/syntaxes/n4js.tmLanguage.yaml, plugins/org.eclipse.n4js.ide/META-INF/MANIFEST.MF, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeSetup.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/imports/ImportsAwareReferenceProposalCreator.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSWorkspaceManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/BuiltInAwareIncrementalBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/WorkspaceAwareResourceLocator.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XWorkspaceManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XIndexer.java, plugins/org.eclipse.n4js.ts.ide/src/org/eclipse/n4js/ts/ide/BuiltInAwareDocumentExtensions.java, plugins/org.eclipse.n4js.ts.ide/src/org/eclipse/n4js/ts/ide/TypesIdeModule.xtend, plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/scoping/builtin/BuiltInSchemeResourceLocator.java, plugins/org.eclipse.n4js.ts/src/org/eclipse/n4js/ts/scoping/builtin/ResourceSetWithBuiltInSchemeProvider.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/xtext/resourceset/XtextResourceLocator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSStandaloneSetup.java
=> [#1647] Support for n4ts in VSCode

lsp-clients/n4js-vscode-extension/package.json, lsp-clients/n4js-vscode-extension/src-gen/extensionProvider.js, lsp-clients/n4js-vscode-extension/src/extensionProvider.n4js, lsp-clients/n4js-vscode-extension/syntaxes/n4js.json.tmLanguage.json, lsp-clients/n4js-vscode-extension/syntaxes/n4js.tmLanguage.json, n4js-libs/packages/n4js-cli/package.json, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java
closes #1670 
also adds syntax highlighting for package.json files
=> GH-1670: As a developer I want VSCode LSP extension to support multiple VSCode instances

n4js-libs/packages/n4js-runtime/src/js/N4RuntimeBootstrap.js, n4js-libs/packages/n4js-runtime/src/n4js/N4BuiltInTypes.n4js, plugins/org.eclipse.n4js.transpiler.es/META-INF/MANIFEST.MF, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/assistants/BootstrapCallAssistant.xtend, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/assistants/ReflectionBuilder.java, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GHOLD_0070_N4Classifier_members_returns_wrong_members.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_03_TestSupport/Parameter_Annotation.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/ChB_N4Objects/Meta_05_N4Classifier.n4js.xt, tests/org.eclipse.n4js.transpiler.es.tests/src/org/eclipse/n4js/transpiler/es/tests/ArrowFunctionTest.xtend, tests/org.eclipse.n4js.transpiler.es.tests/src/org/eclipse/n4js/transpiler/es/tests/BlockTransformationTest.xtend, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/_new_/MetaInfo_jsFunction.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/importexport/IDEBUG_684/AT_IDEBUG_684_NamespacesOptimized_NoDuplicateDeclarartions.n4js.xt
=> GH-574: As a developer I want to limit reflection information on classes in the output code

lsp-clients/n4js-vscode-extension/package.json, lsp-clients/n4js-vscode-extension/syntaxes/n4js.tmLanguage.json
=> GH-1687: As a developer I want TM grammar to support backticks and access modifiers

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSExpressionValidator.xtend
=> GH-1696: Cast expression with syntax error throwing null-pointer exception

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/N4JSIdeContentProposalProvider.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/imports/ImportRewriter.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/imports/ImportsAwareReferenceProposalCreator.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/contentassist/XIdeContentProposalAcceptor.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/proposals/imports/N4JSReplacementTextApplier.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/ImportedElementsScopingHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/PlainAccessOfNamespacedImportDescription.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CamelCaseCompletionTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CompletionWithImportsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractCompletionTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractOrganizeImportsTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractStructuredIdeTest.java
=> GH-1691A: As a smith I want to improve "add missing imports" functionality in code completion and quick fixes

n4js-libs/packages/n4js-runtime/src/n4js/ReflectionBuilder.n4js
=> GH-1712: Nightly build failing due to 3 errors in n4js-libs

releng/utils/scripts/publish-n4js-libs.sh
=> GH-1739: Fix Jenkins to not always increase the version patch segment

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/PostProcessingAwareResource.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/RuntimeDependencyValidationIdeTest.xtend
=> GH-1734: Some tests in bundle org.eclipse.n4js.ide.tests are not executed on Jenkins

n4js-libs/packages/n4js-runtime-fetch/src/n4js/fetch/Method.n4jsd, n4js-libs/packages/n4js-runtime-fetch/src/n4js/fetch/Request.n4jsd, n4js-libs/packages/n4js-runtime-fetch/src/n4js/fetch/RequestInit.n4jsd, n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.ide.test/test/n4js/org/eclipse/n4js/mangelhaft/reporter/ide/test/TestIDEReporter.n4js, n4js-libs/packages/org.eclipse.n4js.mangelhaft.reporter.ide/src/n4js/org/eclipse/n4js/mangelhaft/reporter/ide/IDEReporter.n4js
=> GH-1769: Support arbitrary HTTP methods, add Method.PATCH

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/CustomN4JSParser.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/Issue1756Test.xtend, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/contentAssist/Issue1756PluginUITest.xtend
=> GH-1756: Fixed IOOBE in ContentAssistParser

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java
=> GH-1775: Exceptions in LSP server related to XIndexer$XResolvedResourceDescription

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ModuleWrappingTransformation.xtend, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/Module.xtend, tests/org.eclipse.n4js.xpect.ui.tests/testdata/importexport/folderName_moduleName_clash/SomeProject1/package.json, tests/org.eclipse.n4js.xpect.ui.tests/testdata/importexport/folderName_moduleName_clash/SomeProject1/src/foo.n4js, tests/org.eclipse.n4js.xpect.ui.tests/testdata/importexport/folderName_moduleName_clash/SomeProject1/src/foo/bar.n4js.xt, tests/org.eclipse.n4js.xpect.ui.tests/testdata/importexport/folderName_moduleName_clash/SomeProject2/package.json, tests/org.eclipse.n4js.xpect.ui.tests/testdata/importexport/folderName_moduleName_clash/SomeProject2/src/foo.n4js.xt, tests/org.eclipse.n4js.xpect.ui.tests/testdata/importexport/folderName_moduleName_clash/SomeProject2/src/foo/bar.n4js
=> GH-1780: Transpiler bug when importing modules named after the same folder

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ImportDescriptor.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ImportHelper.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ReferenceResolutionFinder.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/preferences/external/UninstallNpmDependencyButtonListener.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/names/EclipseProjectName.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/names/N4JSProjectName.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/NodeModulesDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ResourceNameComputer.xtend, tests/org.eclipse.n4js.cli.tests/PDTs/npmSimple4.pdt, tests/org.eclipse.n4js.cli.tests/PDTs/yarnDeepPackages1.pdt, tests/org.eclipse.n4js.cli.tests/PDTs/yarnDeepPackages2.pdt, tests/org.eclipse.n4js.cli.tests/PDTs/yarnDeepPackages3.pdt, tests/org.eclipse.n4js.cli.tests/PDTs/yarnDeepPackages4.pdt, tests/org.eclipse.n4js.cli.tests/PDTs/yarnSimple1b.pdt, tests/org.eclipse.n4js.cli.tests/PDTs/yarnSimple3.pdt
=> GH-1787: Project discovery does not find any N4JS projects in certain configurations of a yarn workspace

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XWorkspaceManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/ConcurrentChunkedIndex.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/openfiles/ContainerStructureSnapshot.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/openfiles/OpenFileAllContainersState.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/openfiles/OpenFileContext.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/openfiles/OpenFilesManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderFileChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1788: Imports cannot be resolved in newly created / renamed file when opened

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/LspLogger.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java
See #1795.
Just a small first step that I want to get into the next version of the VSCode extension.
=> GH-1795: As a smith I want some information on the LSP server's health without a host Eclipse

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscFactory.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeSetup.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XBuildManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/BuildCanceledException.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/N4jscTestFactory.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/InProcessExecuter.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCancellationTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
See #1785.
This provides a temporary solution. Final solution is part of `GH-1793`.
=> GH-1785: LSP incremental builder does not rebuild all files if previous build was cancelled

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectStatePersister.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XProjectManager.java
=> GH-1797: Headless builder emits some errors/warnings multiple times

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XBuildContext.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XClusteringStorageAwareResourceLoader.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XIndexer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCancellationTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderFileChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/client/IdeTestLanguageClient.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1789: LSP builder throwing exception after file was renamed/deleted

lsp-clients/n4js-vscode-extension/src-gen/ExtensionProvider.js, lsp-clients/n4js-vscode-extension/src/ExtensionProvider.n4js, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LoggingPrintStream.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java
See #1786.
Reverts #1790 (see first commit below for details).
=> GH-1786: LSP server hanging when unexpected exceptions are thrown (2nd attempt)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/FileSystemScanner.java, tests/org.eclipse.n4js.cli.tests/PDTs/yarnSymLinks.pdt, tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/projectdiscovery/tests/CreateProjectStructureUtils.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/BuilderYarnWorkspaceTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderBasicTest.xtend
=> GH-1805: Compilation problems when using "yarn link"

lsp-clients/n4js-vscode-extension/src/ExtensionProvider.n4js
=> GH-1811: As a developer I want to investigate missing events for watched files

plugins/org.eclipse.n4js.cli/META-INF/MANIFEST.MF, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscFactory.java
=> GH-1818: Multiple instances of @Singletons if the lsp server creates a new connection

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java
=> GH-1824: The LSP server hangs in an infinite loop after the io streams have been closed when started with --stdio

plugins/org.eclipse.n4js.ide/META-INF/MANIFEST.MF, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ImmutableProjectState.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectStatePersister.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/util/IndexedChunkedResourceDescriptions.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/xtext/server/ChunkedResourceDescriptionsTest.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/ide/xtext/server/ProjectStatePersisterTest.java
=> GH-1827: Update the project builder state in one atomic operation

n4js-libs/packages/n4js-mangelhaft-cli/tests/npm-test.sh, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscOptions.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscOptionsValidater.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscCompiler.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSWorkspaceBuilder.java, plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/TestCatalogSupplier.java, plugins/org.eclipse.n4js.tester/src/org/eclipse/n4js/tester/TestDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSGlobals.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/NodeModulesDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/N4jscTestOptions.java, tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/frontend/tests/FrontendCompileTest.java, tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/frontend/tests/FrontendHelpTest.java, tests/org.eclipse.n4js.ide.tests/probands/basic/Test01/package.json, tests/org.eclipse.n4js.ide.tests/probands/basic/Test01/test/ExampleTest.n4js, tests/org.eclipse.n4js.ide.tests/probands/basic/TestCleanPrj1/package.json, tests/org.eclipse.n4js.ide.tests/probands/basic/TestCleanPrj1/test/ExampleTest.n4js, tests/org.eclipse.n4js.ide.tests/probands/basic/TestCleanPrj2/package.json, tests/org.eclipse.n4js.ide.tests/probands/basic/TestCleanPrj2/test/ExampleTest.n4js, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/N4jscTestCatalogGenerationTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/N4jscTestCatalogSideBySideTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/N4jscTestCatalogYarnTest.java
=> GH-1826: As a developer I want to have a convenient way to retrieve the test catalog when working with LSP

n4js-libs/package.json, n4js-libs/yarn.lock
see https://github.com/eclipse/n4js/network/alert/n4js-libs/yarn.lock/dot-prop/open/update-errors/41483147
=> Dependabot-dot-prop: Hotfix for security alert about dot-prop@4.2.0

tests/org.eclipse.n4js.ide.tests/probands/testCatalogIgnoresTestsInNodeModules/P1/node_modules/Test01/package.json, tests/org.eclipse.n4js.ide.tests/probands/testCatalogIgnoresTestsInNodeModules/P1/node_modules/Test01/src/Example.n4js, tests/org.eclipse.n4js.ide.tests/probands/testCatalogIgnoresTestsInNodeModules/P1/node_modules/Test01/test/ExampleTest.n4js, tests/org.eclipse.n4js.ide.tests/probands/testCatalogIgnoresTestsInNodeModules/P1/package.json, tests/org.eclipse.n4js.ide.tests/probands/testCatalogIgnoresTestsInNodeModules/P1/src/A.n4js, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/N4jscTestCatalogIgnoresTestsInNodeModules.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/N4jscTestCatalogIgnoresTestsInNodeModulesTest.java
=> GH-555: Tests from external dependencies must be excluded from test catalog

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ResourceTaskManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderChangesTest.xtend
=> GH-1844: Index changes not propagated correctly after commenting out an interface

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSBuilderFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/BuilderFrontend.java
=> GH-1837: Unnecessary cancellation of the incremental build after saving a file

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/CommandRebuildTest.java
=> GH-1849: Clean does no longer clear issues

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ProjectBuildOrderInfo.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/QueuedExecutorService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ResourceTaskManager.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/BuilderFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ConcurrentIndex.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1853: Fix delay after "initial build done" until all issue markers got deleted in LSP server

tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderFileChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1860-test: Issues persisted in the project state can get out of sync and become incorrect

lsp-clients/n4js-vscode-extension/.vscodeignore, lsp-clients/n4js-vscode-extension/LICENSE, lsp-clients/n4js-vscode-extension/README.md, lsp-clients/n4js-vscode-extension/package.json, n4js-libs/packages/n4js-cli/.gitignore, releng/utils/scripts/build-vscode-extension.sh, releng/utils/scripts/compute-version.sh, version.json
see #1867
(this branch is continued from GH-1866 since during GH-1866 was not merged)
=> GH-1867: As a smith I want to automatically publish the VSCode extension to the marketplace instead of S3

plugins/org.eclipse.n4js.ide/META-INF/MANIFEST.MF, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSLanguageServer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSTextDocumentFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/TextDocumentFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.smith.ui/src/org/eclipse/n4js/smith/ui/SourceMapView.java, plugins/org.eclipse.n4js.tester.ui/src/org/eclipse/n4js/tester/ui/resultsview/TestResultHyperlinkDetector.java, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/sourcemap/SourceMapFileLocator.java, plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/console/N4JSStackTraceHyperlink.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractImplementationTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/symbol/DefinitionTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/symbol/ImplementationTest.java, tests/org.eclipse.n4js.smith.ui.tests/src/org/eclipse/n4js/smith/ui/SourceMapFileLocatorPluginTest.java
=> GH-1870: As a developer I want a command to navigate from an N4JS source file to its generated output file

plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/IN4JSProject.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1869_DynmicImportWithInstalledTypeDefinitions.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/package-info.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/BuilderYarnWorkspaceTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderBasicTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderFileChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderGenerateTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderIndexOnlyTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderWorkspaceChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CompletionWithImportsWorkspaceTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/rename/RenameDisallowedTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractRenameTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractStructuredIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/TestWorkspaceManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/package-info.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/spec/ImportsUnresolvedTest.xtend
=> GH-1869: Dynamic import not fully supported for npm packages with installed type definitions

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XBuildRequest.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCancellationTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1874: Fix issue of invalid null-null-deltas due to resource-creation, build-cancellation, and resource-deletion

lsp-clients/n4js-vscode-extension/src-gen/ExtensionProvider.js, lsp-clients/n4js-vscode-extension/src/ExtensionProvider.n4js, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSBuilderFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/BuilderFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSWorkspaceConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/projectModel/lsp/IN4JSSourceFolder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/ProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/SourceFolderSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/WorkspaceConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/XIProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/XISourceFolder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/XIWorkspaceConfig.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/AbstractIncrementalBuilderTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/GeneratingOutputFileDoesNotTriggerBuildTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderFileChangesTest.xtend
See #1821.
NOTE THE BRANCH NAME! (with a `b`)
=> GH-1821: As a developer I want incremental builds to be triggered when plain JS files change

plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/EObjectDescriptionHelper.java
=> GH-1878: NullPointerException in EObjectDescriptionHelper

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectStatePersister.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCopiedProjectTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderMovedProjectTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/ide/xtext/server/ProjectStatePersisterTest.java
=> GH-1876: The projectstate should use relative URIs based on the location of the projectstate file

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/WorkspaceFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/findReferences/XWorkspaceResourceAccess.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/symbol/XDocumentSymbolService.java
=> GH-1882: Poor time performance when calling "open symbol" in LSP

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/AbstractProcessor.xtend
See #1888.
Maybe there will be a second part for using `unloadAST()`.
=> GH-1888: As a smith I want the builder to not reuse EMF Resources, EObjects, etc.

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectStatePersister.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/ide/xtext/server/ProjectStatePersisterTest.java
=> GH-1886: Fix escaping issue when reading project state files

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/packagejson/PackageJsonResourceDescriptionExtension.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/AbstractPackageJSONValidatorExtension.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/SystemOutRedirecter.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1891: IncrementalBuilderWorkspaceChangesTest can no longer be executed locally

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ImportDescriptor.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ImportHelper.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/codeActions/OrganizeImportsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractOrganizeImportsTest.java
=> GH-1900: Organize imports turns dynamic imports into ordinary namespace imports

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCancellationTest.xtend
=> GH-1905: LSP incremental builder does not rebuild all files if previous build was cancelled (again)

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscMain.java, plugins/org.eclipse.n4js/res/language-version.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageUtils.xtend, releng/utils/scripts/compute-version.sh, releng/utils/scripts/publish-n4js-libs.sh
=> GH-1907: As a smith I want to be able to relate language versions to git commits

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ReferenceResolutionFinder.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CompletionWithImportsWorkspaceTest.xtend
=> GH-1911: As a developer I want newly added imports of plain-JS projects to use complete module specifiers

testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/N4jscTestFactory.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/InProcessExecuter.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java
=> GH-1915: Test "IncrementalBuilderCopiedProjectTest" breaking another, following test

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/FileBasedWorkspaceInitializer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/Project.xtend, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/YarnWorkspaceProject.xtend, tests/org.eclipse.n4js.accesscontrol.tests/src/org/eclipse/n4js/accesscontrol/tests/ScenarioGenerator.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/RebuildFindsNewNpmPackageTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/TestWorkspaceManager.java
See #1914.
This includes two fixes that should make sure that a "N4JS: Rebuild" command will properly pick up newly added/removed dependencies. Does not fix the automatically triggered incremental build (problems related to that are caused by VSCode not sending file-changed-events and thus needs some other solution).
=> GH-1914: As a developer I want the incremental builder to consider newly added/removed dependencies to NPM packages (PART 1)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/N4JSProject.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSProjectConfig.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1923_BogusDuplicateModuleErrorInImplProjects.xtend
=> GH-1923: Bogus "duplicate module" error in modules of implementation projects of API/Impl concept

lsp-clients/n4js-vscode-extension/package.json, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/commands/N4JSCommandService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/ResourceChangeSet.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/BuilderFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectStatePersister.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSWorkspaceConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/XIWorkspaceConfig.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/RebuildFindsNewNpmPackageTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/RefreshTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/TestWorkspaceManager.java
=> GH-1921: As a developer I want a refresh command for the LSP builder

testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/Project.xtend, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/YarnWorkspaceProject.xtend, tests/org.eclipse.n4js.accesscontrol.tests/src/org/eclipse/n4js/accesscontrol/tests/ScenarioGenerator.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1846_InitialBuildShowsMoreErrorsThanIncrementalBuild.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1869_DynmicImportWithInstalledTypeDefinitions.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1923_BogusDuplicateModuleErrorInImplProjects.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/AbstractIncrementalBuilderTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/BuilderYarnWorkspaceTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderBasicTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCancellationTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCopiedProjectTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderFileChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderGenerateTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderIndexOnlyTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderNoCancellationTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderWorkspaceChangesTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/InitialBuildNotCancelableTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/InitialBuildTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/RebuildFindsNewNpmPackageTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/RefreshTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CompletionWithImportsWorkspaceTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/rename/RenameDisallowedTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractRenameTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractStructuredIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/CommandRebuildTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/TestWorkspaceManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/package-info.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/spec/ImportsUnresolvedTest.xtend
=> GH-1926: Provide more defaults in the IDE test infrastructure

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/PreparationStep.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/generator/UnresolvedProxyInSubGeneratorException.java
=> GH-1932: As a developer I want that running 'yarn install' will solve all issues in a running LSP server

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/DebugService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/QueuedExecutorService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java
See #1938.
Just some minor adjustments and fixes for debug information.
=> GH-1938: As a smith I want to collect and investigate errors logged by the LSP server during production use

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1943_ExceptionInCaseOfSemverSyntaxError.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/TestWorkspaceManager.java, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/version/DependencyVersionRequirement/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.ui.tests/xpect/version/error/package.json.xt
=> GH-1943: NullPointerException in case of syntax errors in Semver version strings

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSLanguageServer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/commands/N4JSCommandService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/TextDocumentFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/BuilderFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/util/ParamHelper.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/UnsupportedURIsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1846_InitialBuildShowsMoreErrorsThanIncrementalBuildTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1869_DynmicImportWithInstalledTypeDefinitionsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1923_BogusDuplicateModuleErrorInImplProjectsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1943_ExceptionInCaseOfSemverSyntaxErrorTest.xtend
=> GH-1942: As a developer I want the LSP server to be resilient to unsupported URIs

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscExitCode.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscOptions.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscOptionsValidater.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java
=> GH-1948: Provide more convenient way of starting the LSP server in debug mode

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/util/ServerIncidentLogger.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/documentation/N4JSDocumentationProvider.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/ImportedElementsScopingHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSTypesBuilder.xtend, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_1956_RelinkTModuleLeavingResourceInInvalidState.xtend
=> GH-1956: Relinking TModule leaving resource in invalid state in case of hash mismatch

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/DebugService.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/ImportedElementsScopingHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend
=> GH-1959: As a smith I want to collect and investigate errors logged by the LSP server during production use (no. 2)

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/DefaultBuildRequestFactory.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/IBuildRequestFactory.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XBuildRequest.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/ProjectBuildOrderInfo.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/ProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/WorkspaceChanges.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/WorkspaceConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/XIProjectConfig.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/CyclicDependenciesBuilderTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/InitialBuildNotCancelableTest.xtend
=> GH-1967: As a smith I want update events from changes in package.json to be propagated to other package.json

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/CustomN4JSParser.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/LspLogger.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSTextDocumentFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/util/ServerIncidentLogger.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/XLanguageServerImpl.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/SuppressAccessInfoTest.xtend
=> GH-1976: Content assist shows too many entries in some situations

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSOutputConfigurationProvider.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSConfigSnapshotFactory.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/DefaultBuildRequestFactory.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSGlobals.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/generator/AbstractSubGenerator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/lsp/N4JSProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/PackageJsonValidatorExtension.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/ConfigSnapshotFactory.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/ProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/xtext/workspace/XIProjectConfig.java, tests/org.eclipse.n4js.ide.tests/probands/n4jsx/react/package.json, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/ProjectWithoutGenerationBuilderTest.xtend
=> GH-1987: Definition projects are not validated and clean sometimes deletes entire project contents

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/ImportsAwareReferenceProposalCreator.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CamelCaseCompletionTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CompletionWithImportsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/SuppressAccessInfoTest.xtend
=> GH-1989: Set missing icons for some content assist proposals

plugins/org.eclipse.n4js.model/src/org/eclipse/n4js/n4JS/DestructNode.xtend, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/EcoreUtilN4.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/DestructureHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSDestructureValidator.xtend, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_1996_ReflexiveReferenceInDefaultValueOfObjectDestructuring.n4js.xt
=> GH-1996: Reflexive reference in default value of object destructuring binding patterns causing havoc

n4js-tools/@n4js-temp/n4jsd-generator/src/cmdLineOpts.ts, n4js-tools/@n4js-temp/n4jsd-generator/src/convert.ts, n4js-tools/@n4js-temp/n4jsd-generator/src/main.ts, n4js-tools/@n4js-temp/n4jsd-generator/src/model.ts, n4js-tools/@n4js-temp/n4jsd-generator/src/utils_ts.ts
See #1994.
Contains:
- a bug fix.
- support for default imports/exports.
=> GH-1994: As a smith I want to extend and internally publish the n4jsd-generator (part 2)

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/util/ServerIncidentLogger.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/organize/imports/ScriptDependencyResolver.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/AbstractProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/ImportedElementsScopingHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/AbstractPackageJSONValidatorExtension.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend
See #2001.
Some smaller fixes and adjustments that do not require a separate ticket.
For the long-time TODO's in the code (removing temporary debug logging, etc.) I created a dedicated ticket, see `GH-2002` and adjusted the references in the code.
=> GH-2001: As a smith I want to collect and investigate errors logged by the LSP server during production use (no. 3)

releng/org.eclipse.n4js.targetplatform/N4JS.setup
=> Cannot install developer Eclipse due to ssl problem with Bash Editor

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/Reducer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/RuleEnvironmentExtensions.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/StructuralTypingComputer.xtend, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_2029_TwoBugsCausedByRecursiveStructuralTypes.n4js.xt, tests/org.eclipse.n4js.xsemantics.tests/src/org/eclipse/n4js/xsemantics/caching/PerformanceSubtypeTest.xtend
=> GH-2029: Two bugs caused by recursive structural types

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscMain.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/PatchedRemoteEndpoint.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/internal/FileBasedWorkspace.java
=> GH-2033: ConcurrentModificationException in FileBasedWorkspace

plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/editor/hyperlinking/packagejson/PackageJsonHyperlinkHelperExtension.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonContentProvider.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonProperties.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionLoader.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractIdeTest.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/TestWorkspaceManager.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/buildorder/BuildOrderWorkspacesExtendedTest.xtend, tests/org.eclipse.n4js.json.tests/src/org/eclipse/n4js/json/tests/ide/contentassist/JSONCompletionTest.xtend, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/yarn-workspaces/workspacesArray/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.tests/xpect/yarn-workspaces/workspacesObject/package.json.xt, tests/org.eclipse.n4js.packagejson.xpect.ui.tests/xpect/contentassist/package.json.xt
=> GH-2042: Some legal values of yarn's "workspaces" property in package.json not supported

plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/codegen/YarnWorkspaceProject.xtend
=> GH-2042-fix: Some legal values of yarn's "workspaces" property in package.json not supported

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/StructuralMembersTripleIterator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_03__StructuralTyping/StructuralTypingExtension_StructuralSubtypeCheckWithSetter.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_03__StructuralTyping/StructuralTypingExtension_SubtypeMatrix.n4js.xt
=> GH-2048: Fix subtype check on identical type refs

n4js-libs/packages/n4js-runtime-esnext/src/n4js/Array.n4jsd
=> GH-1852: Adding flatMap, flat, includex, copyWithin, fill

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/ContentAssistDataCollectors.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ReferenceResolutionFinder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSTextDocumentFrontend.java, plugins/org.eclipse.n4js.smith/src/org/eclipse/n4js/smith/CollectedDataAccess.java
=> GH-2065: Improve time measurements for slow content assist

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-2067: As a smith I want to remove all bundles/files necessary only for the Eclipse product (without refactoring) (part 3)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSResourceValidator.java
closes #2075 
This PR replaces https://github.com/eclipse/n4js/pull/2076
=> GH-2075: ClassCastException on issues created by N4JSResourceValidator

plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSLanguageConstants.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtFileData.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtFileDataParser.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtFileRunner.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtIdeTest.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtMethodsIssues.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtParentRunner.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtSetupParser.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtSetupWorkspaceParser.java, tests/org.eclipse.n4js.flowgraphs.tests/src/org/eclipse/n4js/flowgraphs/tests/FlowgraphsXtTest.java, tests/org.eclipse.n4js.ide.tests.helper.tests/probands/IssueConfiguration/IssueConfiguration.n4js.xt, tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/AbstractXtParentRunnerTest.java, tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/IssueConfigurationTest.java, tests/org.eclipse.n4js.ide.tests.helper.tests/src/org/eclipse/n4js/ide/tests/helper/server/xt/tests/debug/IdeTestsHelperXtTest_.java, tests/org.eclipse.n4js.packagejson.xpect.tests/src/org/eclipse/n4js/packagejson/xpect/tests/PackageJsonXtTest.java, tests/org.eclipse.n4js.spec.tests/src/org/eclipse/n4js/spec/tests/SpecXtTest.java, tests/org.eclipse.n4js.ts.xpect.tests/src/org/eclipse/n4js/ts/tests/XtTsTest.java, tests/org.eclipse.n4js.xpect.tests/src/org/eclipse/n4js/xpect/tests/N4jsXtTest.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/linking/Brother.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/linking/Sister.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/linking/anon_functions.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/project_circular_dependencies/packageA.json.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/project_circular_dependencies/packageA_decyclic.json.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/project_circular_dependencies/packageB.json.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/project_circular_dependencies/packageC.json.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/project_circular_dependencies/packageD.json.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/resourcedescriptions/Brother.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/resourcedescriptions/Sister.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/scoping/Brother.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/scoping/Sister.n4js.xt
=> GH-2087: As a smith I want support for issue suppression on a per-file basis in Xt test files

releng/org.eclipse.n4js.targetplatform/N4JS.setup
=> GH-2086: Broken image link in the project's Oomph setup.

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/PatchedLauncherBuilder.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/PatchedTracingMessageConsumer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/imports/ReferenceResolutionFinder.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/collections/Iterables2.xtend, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/ResourceTaskManager.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/TextDocumentFrontend.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/contentassist/XIdeContentProposalAcceptor.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/NonResolvingImportScope.java
See #2099.
NOTE: to get the straightforward fixes to master asap, I have reverted two changes that require further investigation/consideration, see 82e082b. Issue #2099 will remain open, for now.
=> GH-2099: Content assist does not react to cancellation in a timely manner

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/TrimTransformation.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_exported.n4js.xt
=> GH-2101: type alias leaves export statement in transpiled output

tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/IDEBUG_0191_prototypeOutput.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch07_04__Reflection_Meta_Information/AnnotationsInfo.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch11_03__TestSupport/Parameter_Annotation.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch18__N4JSObjects/Meta_01_N4Object.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/annotations/IDEBUG_246_DescriptionWithSingleQuote.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/annotations/IDEBUG_246_DescriptionWithSingleQuoteEscaped.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/annotations/IDEBUG_246_DescriptionWithSingleQuoteUnicode.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/classes/AT_634_ClassMeta.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/classes/AT_874_InheritConstructor/AT_874_InheritFromBuiltInType.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/classes/AT_953_alias/AT_953_AliasIdentRef3.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/importexport/IDEBUG_684/AT_IDEBUG_684_NamespacesOptimized_NoUnusedNamespace_CommonJS.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/importexport/IDEBUG_684/AT_IDEBUG_684_NamespacesOptimized_NoUnusedNamespace_SystemJS.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/classes/N4ClassDeclAsAnnotatedExportableElement.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/classes/N4ClassDeclAsAnnotatedScriptElement.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/classes/N4ClassDeclAsExportedN4ClassDeclaration.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/classes/N4ClassDeclAsScriptElement.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/enums/EnumAsAnnotatedExportableElement.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/n4members/n4membersAbstractMethod.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/n4members/n4membersAnnotatedAbstractMethod.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/n4jsTokenRemoval/roles/N4RoleDeclAsAnnotatedExportableElement.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/reflection/ClassMembers.n4js.xt, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/reflection/InterfaceMembers.n4js.xt
=> GH-2103: As a smith I want to update node.js to version 14

n4js-libs/packages/n4js-runtime-html5/src/n4js/ClipboardEvent.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/ErrorEvent.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/Event.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/KeyboardEvent.n4jsd, n4js-libs/packages/n4js-runtime-html5/src/n4js/TouchEvent.n4jsd
=> GH-2105: Add HTML5 ErrorEvent (part 2)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend, tests/org.eclipse.n4js.spec.tests/xt-tests/GH_2116_ReactElementChangedToStructGenericInterface.n4jsx.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Req241116_JSXElements_Referring_to_React_Components.n4jsx.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/reactWithModifications/README.txt, tests/org.eclipse.n4js.spec.tests/xt-tests/reactWithModifications/index.n4jsd, tests/org.eclipse.n4js.spec.tests/xt-tests/reactWithModifications/package.json
=> GH-2116: JSX validation showing bogus error when React.Element is changed from class to interface

plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/ResourceTaskManager.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/ConcurrentIndex.java, plugins/org.eclipse.n4js.xtext/src/org/eclipse/n4js/xtext/workspace/ConfigSnapshotFactory.java, plugins/org.eclipse.n4js.xtext/src/org/eclipse/n4js/xtext/workspace/ProjectSet.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSWorkspaceConfig.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderShadowingTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/xtext/workspace/ProjectSetTest.java
=> GH-2121: Exceptions when creating/deleting a workspace project that shadows a node_modules project

tests/org.eclipse.n4js.ide.tests/probands/external_project_dependencies/P1/package.json, tests/org.eclipse.n4js.ide.tests/probands/external_project_dependencies/P2/package.json, tests/org.eclipse.n4js.ide.tests/probands/external_project_dependencies/P2/src/Y.n4jsx, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/N4jscDependentProjectDependenciesTest.java
=> GH-2124: Nightly failing after type definitions in Git repository "n4jsd" have been changed

plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/ResourceTaskContext.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/ResourceTaskManager.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/TextDocumentFrontend.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/issues/WorkspaceValidateListener.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/bugreports/GH_2130_EditorInvalidAfterFollowingHyperlink.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/xtext/server/ResourceTaskManagerIdeTest.xtend
=> GH-2130: Editor opened in invalid state after following hyperlinks

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/ThisTypeComputer.xtend, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_2126_ValueOfThisInFunctionAssignableToEverything.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/array/array_some.n4js.xt, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/scoping/UndefinedHandlingTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/xsemantics/JudgmentTypeTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/xsemantics/N6_1_01_ThisKeywordInArrowExpressionTest.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/xsemantics/N6_1_01_ThisKeywordTest.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Others/asyncFunctionsAndMethods/AsyncThisBinding.n4js.xt
=> GH-2126: Value of this-keyword in functions is assignable to everything

tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/YarnProjectDuplicateNames.xtend
=> GH-2143: Yarn project ignored iff a sub project exists with the same name

plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/issues/DiagnosticComparator.java, tests/org.eclipse.n4js.ide.tests/probands/GH-2154/TestProject/package.json, tests/org.eclipse.n4js.ide.tests/probands/GH-2154/TestProject/src/TestModule.n4js, tests/org.eclipse.n4js.ide.tests/probands/external_project_dependencies/P2/package.json, tests/org.eclipse.n4js.ide.tests/probands/external_project_dependencies/P2/src/Y.n4jsx, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/compiler/AT_GH_2154_HeadlessBuilderNotShowingAllIssues.java
=> GH-2154: Headless builder sometimes not showing all issues

docs/org.eclipse.n4js.design/chapters/03_releng/releng.adoc
=> GH-2159: As a smith I want to create a list of all n4js dependencies and their licenses

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/hover/N4JSHoverService.java, plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/ReturnTypeTransformation.xtend, plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/TypeReferenceTransformation.xtend, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/assistants/TypeAssistant.xtend, tests/org.eclipse.n4js.spec.tests/xt-tests/dts/inferredTypes/InferredTypes1.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts/typeRefs/SpecConstructor.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts/typeRefs/ThisTypeRef.n4js.xt
=> GH-2171: Small bugs in .d.ts export

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscMain.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscOptions.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/N4jscTestFactory.java, tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/frontend/tests/FrontendCompileTest.java, tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/frontend/tests/FrontendHelpTest.java, tests/org.eclipse.n4js.cli.tests/src/org/eclipse/n4js/cli/frontend/tests/FrontendLspTest.java
=> GH-2175: Regression due to GH-2164: compiler not stopping after printing out version with given option --version

n4js-libs/packages/n4js-mangelhaft-cli/src/n4js/org/eclipse/n4js/mangelhaft/runner/node/NodeTestRunner.n4js, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSGlobals.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java
=> GH-2178: Allow API projects to be defined by suffix "-api" (in addition to suffix ".api")

plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/TypeReferenceTransformation.xtend, tests/org.eclipse.n4js.spec.tests/xt-tests/dts/typeRefs/IterableN.n4js.xt
=> GH-2184: As a TS-developer I want an improved handling of IterableN types

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubstTypeVariablesJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/Reducer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/SubtypeComputer.xtend, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_2200_ConstraintSolverConfusedByUnion.n4js.xt, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/typesystem/InferenceContextTest.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_genericAlias_appliedInGenericFunction.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_genericAlias_openExistentialInFunTypeExprOrRef.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_genericAlias_openExistentialInStructTypeRef.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_genericAlias_openExistentialInTypesOfReact.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_genericAlias_substitution.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_recursive.n4js.xt
See #2200.
NOTE: this actually includes fixes for two separate problems, see issue for details.
=> GH-2200: Constraint solver confused by certain special cases of union types

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSMemberRedefinitionValidator.java, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch05_02_06__Redefinition_of_Members/MemberRedefinition_accessibilityOfOverriddenMember1.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch05_02_06__Redefinition_of_Members/MemberRedefinition_accessibilityOfOverriddenMember2.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch05_02_06__Redefinition_of_Members/MemberRedefinition_accessibilityOfOverriddenMember3.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch05_02_06__Redefinition_of_Members/MemberRedefinition_accessibilityOfOverriddenMember_Other.n4js
=> GH-2210: Exception in N4JSMemberRedefinitionValidator

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/accessModifiers/MemberVisibilityChecker.java
=> GH-2217: ClassCastException during content assist

docs/org.eclipse.n4js.spec/chapters/12_components/components.adoc, plugins/org.eclipse.n4js.json.model/src/org/eclipse/n4js/json/model/utils/JSONModelUtils.java, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/EcmaScriptSubGenerator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonProperties.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescription.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescriptionBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/PackageJsonValidatorExtension.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractIdeTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/misc/NoSourcemapsTest.java, tests/org.eclipse.n4js.json.tests/src/org/eclipse/n4js/json/tests/ide/contentassist/JSONCompletionTest.xtend
=> GH-2243: As a developer I want an option to turn off source maps

releng/utils/scripts/compute-version.sh, releng/utils/scripts/publish-n4js-libs.sh
See #2250.
NOTE: the main changes are in scripts that reside in another repository, so only few changes here.
=> GH-2250: Minor adjustments in publishing scripts to allow publishing from a branch with dist-tag "latest"

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/analysers/InstanceofGuardAnalyser.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/guards/GuardFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/guards/GuardMerger.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/guards/GuardStructureFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/guards/InstanceofGuard.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtMethodsFlowgraphs.java, tests/org.eclipse.n4js.xpect.tests/xpect-tests/validation/controlflow/Instanceof_Guard.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xpect-tests/validation/controlflow/Instanceof_Guard_disjunctions.n4js.xt
=> GH-2245: As a developer I want type guards to support disjunctions via logical or expressions resulting in union types

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/guards/GuardStructure.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/EcoreUtilN4.java
=> GH-2253: Elaborate on call to EcoreUtil2.getAllContentsOf in GuardStructure#getGuardList

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/WorkspaceAccess.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/validation/GH_2259_PackageJsonValidationMustNotLoadFromSourceTest.xtend
=> GH-2259: Package.json validations showing bogus errors in incremental headless build

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/XpectAwareFileExtensionCalculator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/validation/VeeScopeValidator.java
=> GH-2272: Wrong binding in rare situations when an identifier can bind to both value and type

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSDeclaredNameValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSMemberRedefinitionValidator.java
=> GH-2271: Poor performance of validation N4JSDeclaredNameValidator#checkNameConflicts() in case of many types/values of same name

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/ExpectedTypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/TypeSystemHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSTypeValidator.xtend, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_2275_SpecArgumentValidationThrowingNullPointerException.n4js.xt, tests/org.eclipse.n4js.bugreports.tests/bugreports-tests/GH_2275_SpecArgumentValidationThrowingNullPointerException_Other.n4jsd
=> GH-2275: Spec argument validation throwing NullPointerException when using construct signature

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/N4JSIdeModule.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSResourceTaskContext.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/ResourceTaskContext.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java
=> GH-2280: Slightly improve compile time performance by skipping function bodies of external n4js/x files

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/ContentAssistTokenTypeMapper.java
=> GH-2282: Parser bug caused by some characters

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-2285: Update outdated repo urls in oomph project setup

plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/ImmutableDataClass.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDependency.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescription.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/SourceContainerDescription.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/utils/SemanticDependencySupplier.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/workspace/SemanticDependenciesTest.xtend
=> GH-2287: Incorrect equality check in ImmutableDataClass

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscLanguageClient.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/N4JSFlowAnalyser.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/analysis/GraphVisitorAnalysis.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/analysis/SuccessorPredecessorAnalysis.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/FlowGraph.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/DtsAfterBuildListener.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSProjectBuilder.java, plugins/org.eclipse.n4js.jsdoc2spec/src/org/eclipse/n4js/jsdoc2spec/adoc/RepoRelativePathHolder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/DefaultBuildRequestFactory.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XBuildRequest.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XIncrementalBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XStatefulIncrementalBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSFlowgraphValidator.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/N4jsLibsAccess.java
=> GH-2314: As a smith I want the new N4JS compiler to not use more memory than the old one

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSProjectBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/UserDataMapper.java
follow-up of GH-2318-mm that fixes a last open issue
=> GH-2318-mm: As a developer I want support for module declarations in d.ts

releng/org.eclipse.n4js.targetplatform/N4JS.setup, releng/org.eclipse.n4js.targetplatform/org.eclipse.n4js.targetplatform.target
=> GH-2333: Fix broken dependency to xtext

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsBuilderWithHelpers.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsNamespaceBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsClassBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsInterfaceBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsScriptBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/utils/ParserContextUtils.java
closes #2339 this PR closes the user story.
=> GH-2339: As a developer I want to replace some @n4jsd packages with @types packages (part 2) 

plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/TypeReferenceTransformation.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSDeclaredNameValidator.xtend, tests/org.eclipse.n4js.spec.tests/xt-tests/dts/FunctionDeclaration_withOptionalReturnType.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts/typeRefs/FunctionTypeExpression_withOptionalReturnType.n4js.xt
=> GH-2347: Functions with optional return value handled incorrectly by .d.ts export

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/rename/N4JSRenameService.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractRenameTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/rename/RenameReactPropsTest.xtend
=> GH-2082: vscode ext: Renaming symbol on a react prop adjusts all code usages apart from JSX props

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/builtin/BuiltInTypeScope.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/ExpectedTypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/RuleEnvironmentExtensions.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_13_02__StringBasedEnums/Req41_NumberBasedEnums_Usage.n4js.xt
=> GH-2266: Some special handling for @NumberBased enums missing

plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ASTMetaInfoCache.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/AbstractFunctionDefinitionTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSFormalParameterTypesBuilder.xtend
=> GH-2328: Execption during "documentHighlight" after relinking AST

plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/UserDataMapper.java
See #2367.
This PR contains only a very small change: adjustment of a debug message.
Main PR: #2368.
=> GH-2367: As a smith I want to investigate and solve/mitigate loading from source triggered on d.ts files in editors

plugins/org.eclipse.n4js/src/org/eclipse/n4js/tooling/organizeImports/ScriptDependencyResolver.xtend
=> GH-2377: ClassCastException when using d.ts files from npm package 'immutable'

plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/print/PrettyPrinterEcmaScript.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-parser/user-tests/exports/reexport_transpiler.n4js.xt
=> GH-2381: Transpiler emits bogus output code for property access on element re-exported from .d.ts

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/ExportedElementsCollector.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/N4JSScopeProvider.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/ImportedElementsScopingHelper.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/scoping/ExportDefinitionTest.xtend, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/exports/exportEquals05_reexport_namespacePlusVariable.n4js.xt
=> GH-2388: Chaining "export =" and re-exports in .d.ts files does not work

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsPropertyNameBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/utils/ParserContextUtils.java
=> GH-2395: Relinking d.ts files causes IllegalStateException due to computed property names

plugins/org.eclipse.n4js.smith/src/org/eclipse/n4js/smith/N4JSDataCollectors.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/NestedTypeRefsSwitch.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/RuleEnvironmentExtensions.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_14__TypeAlias/TypeAlias_recursive_2.n4js.xt
=> GH-2415: Type alias recursion causes StackOverflowError

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSStatefulIncrementalBuilder.java, plugins/org.eclipse.n4js.smith/src/org/eclipse/n4js/smith/N4JSDataCollectors.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XWorkspaceManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResourceDescriptionManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/PackageJsonResourceDescriptionExtension.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/CyclicDependenciesBuilderNoRebuildTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/InitialBuildNotCancelableTest.xtend
=> GH-2414: As a smith I want to investigate why the initial build of an already-built project takes >1 min

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/CamelCasePrefixMatcher.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/ModuleSpecifierProposalCreator.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/N4JSIdeContentProposalProvider.java, plugins/org.eclipse.n4js.model/src/org/eclipse/n4js/n4JS/N4JSMetaModelUtils.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/contentassist/XContentAssistService.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CamelCaseCompletionTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/CompletionWithImportsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/ImportSpecifierCompletionTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/contentassist/NamespaceCompletionTest.xtend
=> GH-2420: As a developer I want content assist for module specifiers

docs/org.eclipse.n4js.design/chapters/02_eclipseSetup/eclipseSetup.adoc
This story is about an internal build setup migration.
=> As a smith I want to migrate to a new AWS S3 Bucket

plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ContainerTypesHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/DeclMergingHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/DeclMergingUtils.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/resource/ImportedNamesTest.xtend, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/merge_with_globals_from_n4jsd.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/misc/prioritizeBuiltInTypesOverGlobalDtsElements01.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/misc/prioritizeBuiltInTypesOverGlobalDtsElements02.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/misc/prioritizeBuiltInTypesOverGlobalDtsElements03.n4js.xt
=> GH-2423: As a developer I want support/handling for declaration merging with existing global type definitions

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/symbol/N4JSHierarchicalDocumentSymbolService.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractDocumentSymbolTest.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/StringLSP4J.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/symbol/DocumentSymbolTest.java
=> GH-2427: As a developer I want LSP Document Symbols (used in outline view) to show reasonable information

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/SanitizeImportsTransformation.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/ExportedElementsCollector.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSImportValidator.xtend, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/directReferenceToElementOfOtherDeclModuleWithProjectImport.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/no_merge_two_dependency_versions.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/project_augmentation/augment_extern_use_extern_other_import.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/project_augmentation/augment_extern_use_extern_other_import_v2.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/project_augmentation/augment_extern_use_intern.n4js.xt
=> GH-2430: Declaration merging not working for re-exported modules

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsScriptBuilder.java, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ModuleSpecifierTransformation.xtend, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/StaticPolyfillTransformation.xtend, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/TranspilerBuilderBlocks.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/RuntimeDependencyProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResourceDescriptionStrategy.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/imports/AmbiguousImportDescription.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/DeclMergingHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/DeclMergingUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/WorkspaceAccess.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/import_module_specifier_of_merged_script.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/polyfill_default_import.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/polyfill_importing_merged_modules.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/polyfill_importing_reexported_module_with_decl_merging.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/polyfill_importing_reexported_modules.n4js.xt
=> GH-2432: Missing import in output js code when importing from polyfills with re-exports

plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/ExistentialTypeRef.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/TypeRefsPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/ExistentialTypeRefImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefsFactoryImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefsPackageImpl.java, plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/N4JSScopeProviderLocalOnly.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/types/utils/TypeUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeJudgment.java
=> GH-2443: IllegalArgumentExceptions when converting EObjectDescriptions containing UUIDs

plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonProperties.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionLoader.java, tests/org.eclipse.n4js.json.tests/src/org/eclipse/n4js/json/tests/ide/contentassist/JSONCompletionTest.xtend, tests/org.eclipse.n4js.xpect.tests/xt-tests/packagejson_type_defs/type_defs_defined_in_pcksjon_exports.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/packagejson_type_defs/type_defs_defined_in_pcksjon_types.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/packagejson_type_defs/type_defs_defined_in_pcksjon_types_folder.n4js.xt
=> GH-2445: Support package.json property 'types' and consequently module separation of implementation and type definitions

plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/ModuleSpecifierForm.java, plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/impl/N4JSPackageImpl.java, plugins/org.eclipse.n4js.model/model/N4JS.xcore, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ModuleSpecifierTransformation.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonProperties.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescription.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescriptionBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectExports.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ImportSpecifierUtil.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/packagejson_type_defs/pcksjon_exports_virtual_project.n4js.xt
=> GH-2445-B: Support package.json property 'types' and consequently module separation of implementation and type definitions

plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonProperties.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescription.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectDescriptionBuilder.java, tests/org.eclipse.n4js.json.tests/src/org/eclipse/n4js/json/tests/ide/contentassist/JSONCompletionTest.xtend, tests/org.eclipse.n4js.xpect.tests/xt-tests/packagejson_type_defs/type_defs_defined_in_pcksjon_typesVersions.n4js.xt
=> GH-2448: Support package.json property 'typesVersions' that defines a source path to definition files

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/DtsParser.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsModuleRefBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSStatefulIncrementalBuilder.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/naming/N4JSQualifiedNameProvider.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSResource.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfigSnapshot.java, tests/org.eclipse.n4js.integration.tests/src/org/eclipse/n4js/integration/tests/dts/DtsParsesDefinitelyTypedTest.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/module_augmentation/augmentation_ok2.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/module_augmentation/augmentation_ok2_A.d.ts, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/module_augmentation/augmentation_ok2_typesVersions.n4js.xt
=> GH-2450: Unable to import merged-in type elements of exported Interfaces (d.ts)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/Reducer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/SubtypeComputer.xtend, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch08_01_10__FunctionCalls/polyprocessor_callable_interfaces.n4js.xt
=> GH-2456: As a developer I want the poly processor to resolve generics in callable interfaces

plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/IntersectionTypeExpression.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/TypeRefsPackage.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/IntersectionTypeExpressionImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/TypeRefsPackageImpl.java, plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/GenericsComputer.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/StructuralTypesHelper.xtend, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/array/array_reduce.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/array/array_reduceRight.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_defineProperty.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_freeze.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_getOwnPropertyDescriptor.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_isFrozen.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_isSealed.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/builtin_js/object/object_seal.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Await/Async-ArrowFunctionTypeChecking.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Await/Async-inlineFunctionTypeChecking.n4js.xt, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Class_x_Generics_US/03_methods_returning_functions.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/polyprocessor_struc_obj_union_props.n4js.xt
=> GH-2459: Polyprocessor fails to confirm subtype relation in case of properties typed as union types

plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/TypeSystemHelper.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_11__ConstructorAndClassifierType/Composed_Types_are_constructors.n4js.xt
=> GH-2464: Cannot use valid composed types as constructor

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/UnionMemberDescriptionWithError.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/AbstractDescriptionWithError.java, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_10__UnionType/UnionTypeMemberAccess_static_member_in_union.n4js.xt
closes #2466
The error message turned out to be unclear.
=> GH-2466: Cannot access members of unions when any+ is one of the composed types

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend, tests/org.eclipse.n4js.xpect.tests/xt-tests/ReactElementAnyPlus.n4jsx.xt
=> GH-2476: Allow any+ typed elements for use as react elements

plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/FlowAssertionFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/dataflow/symbols/SymbolFactory.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/factories/CFEMapper.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/ComplexNode.java, plugins/org.eclipse.n4js.flowgraphs/src/org/eclipse/n4js/flowgraphs/model/FlowGraph.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/codeActions/N4JSCodeActionService.java, plugins/org.eclipse.n4js.ts.model/src/org/eclipse/n4js/ts/types/util/AbstractTypeHierachyTraverser.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSCache.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/SourceElementExtensions.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/AllSuperTypeRefsCollector.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ContainerTypesHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageUtils.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_03__StructuralTyping/FieldsOptionalThroughConditional.n4js.xt
=> GH-2472: As a developer I want optional field strategy to support conditional expressions

plugins/org.eclipse.n4js.ts.model/src/org/eclipse/n4js/ts/types/util/TypeExtensions.java, plugins/org.eclipse.n4js.ts.model/src/org/eclipse/n4js/ts/types/util/TypeUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/N4JSCache.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/types/utils/TypeUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/ThisTypeComputer.xtend, tests/org.eclipse.n4js.expectmatrix.tests/xpect-tests/matrix/Class_x_This/01_in_methods.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_11__ConstructorAndClassifierType/ConstructorType_static_method.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_12__ThisType/AT-IDE0785_ThisType_in_static_return_with_variables.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_12__ThisType/AT-IDE0785_ThisType_in_type_expressions.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_02_02_03__CovariantConstructors/CovariantConstructors_thisType.n4js.xt
=> GH-2474: As a developer I want the type of 'this' in static methods of a class C to be 'constructor{this[C]}'

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/lsp/LspServer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/symbol/N4JSDocumentSymbolService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/symbol/N4JSWorkspaceSymbolService.java, plugins/org.eclipse.n4js.json.ide/src/org/eclipse/n4js/json/ide/symbol/JSONHierarchicalSymbolService.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/symbol/XDocumentSymbolService.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/SystemExitRedirecter.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractDocumentSymbolTest.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractWorkspaceSymbolTest.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/StringLSP4J.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/UnsupportedURIsTest.xtend, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/symbol/DocumentSymbolTest.java
=> GH-2484: As a smith I want to fix deprecation warnings introduced by update of LSP4J

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSTextDocumentFrontend.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/rename/N4JSRenameService.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/symbol/N4JSDocumentSymbolService.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSEObjectAtOffsetHelper.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/AbstractRenameTest.java
=> GH-2496: Rename refactoring always returns "Element can't be renamed"

plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/AbstractPolyProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageUtils.xtend, tests/org.eclipse.n4js.xpect.tests/xpect-tests/typesystem/polyExpressions/CondExpr.n4js.xt
=> GH-2469: As a developer I want the poly processor to also support conditional expressions

plugins/org.eclipse.n4js.model/emf-gen/org/eclipse/n4js/n4JS/ParameterizedAccess.java, plugins/org.eclipse.n4js.model/model/N4JS.xcore, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/ParameterizedTypeRef.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/ParameterizedTypeRefImpl.java, plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore, plugins/org.eclipse.n4js.ts.model/src/org/eclipse/n4js/ts/types/util/TypeModelUtils.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/AbstractPolyProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor_CallExpression.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/ExpectedTypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/TypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/GenericsComputer.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/TypeSystemHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageUtils.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/ASTStructureValidator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSTypeValidator.xtend, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/parser/OptionalTypeParameterParserTest.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch05_01_05__Generic_Classifiers/OptionalTypeParameters_validations_legalUseCases.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch06_05_01__GenericFunctions/Function_OptionalTypeArgs.n4js.xt
=> GH-2453: As a developer I want to use default type arguments in functions/etc.

plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/ASTStructureValidator.xtend, tests/org.eclipse.n4js.transpiler.es5.tests/testdata/expressions/BinaryExpression.n4js.xt
=> GH-2504: Fix RuntimeException thrown in generator due to illegal script

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsBuilderWithHelpers.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsTypeRefBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/utils/ParserContextUtils.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtMethods.java, tests/org.eclipse.n4js.xpect.tests/src/org/eclipse/n4js/xpect/tests/N4jsXtTest.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/typeRefs/PromiseTypeRef.n4js.xt
=> GH-2508: Fix compiler exception due to d.ts term Promise<void>

n4js-tools/n4jsd-generator/package.json, n4js-tools/n4jsd-generator/src/n4js/utils.n4js, n4js-tools/n4jsd-generator/yarn.lock
=> GH-2503: Fix js issues in n4js-tools

n4js-libs/packages/n4js-cli/src/n4js/index.n4js
=> GH-2524: Infinitive loop in libs method of n4js-cli

plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/ConcurrentIndex.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java
=> GH-2530: Default project type must be 'library' iff project nature is N4JS

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/DtsParser.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/NestedResourceAdapter.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/RootNode.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsNamespaceBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/DtsScriptBuilder.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSTextDocumentFrontend.java, plugins/org.eclipse.n4js/src-env/env/builtin_js.n4jsd, plugins/org.eclipse.n4js/src/org/eclipse/n4js/compileTime/CompileTimeEvaluator.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/ComputedNameProcessor.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSFieldTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSGetterTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSMethodTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSSetterTypesBuilder.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesbuilder/N4JSTypesBuilderHelper.xtend, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/AllDirectStructuralSuperTypeRefsCollector.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/AllSuperTypeRefsCollector.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/BaseJavaScriptVariantHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/JavaScriptVariantHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/N4JSJavaScriptVariantHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSMemberRedefinitionValidator.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/declMerging/GH-2536.n4jsd.xt
=> GH-2536: Warning CLF_MISSING_IMPLEMENTATION_EXT issued on external class extending a d.ts class

plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsModuleRefBuilder.java, plugins/org.eclipse.n4js.dts/src/org/eclipse/n4js/dts/astbuilders/AbstractDtsNamespaceBuilder.java, plugins/org.eclipse.n4js.model/src/org/eclipse/n4js/n4JS/N4JSASTUtils.java, plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/print/PrettyPrinterDts.java, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/print/PrettyPrinterEcmaScript.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/parser/conversion/ModuleSpecifierValueConverter.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/UserDataMapper.java, tests/org.eclipse.n4js.integration.tests/src/org/eclipse/n4js/integration/tests/dts/DtsParsesDefinitelyTypedTest.java
=> GH-2545: Serialization of module references that contain ':' cause problems

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ExpressionTransformation.xtend, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/TranspilerBuilderBlocks.xtend, plugins/org.eclipse.n4js.transpiler/src/org/eclipse/n4js/transpiler/print/PrettyPrinterEcmaScript.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/messages.properties, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSExpressionValidator.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch08_02_02__TemplateLiterals/TaggedTemplateStrings.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch08_04_02__OptionalChaining/OptionalChaining.n4js.xt
=> GH-2547: Deactivate transpiling of optional chaining and coalesce expressions

plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/members/MemberScopingHelper.xtend, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_10__IntersectionType/AnyPlus_intersection.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_10__IntersectionType/AnyPlus_union.n4js.xt, tests/org.eclipse.n4js.spec.tests/xpect-tests/Ch04_10__IntersectionType/Double_intersection.n4js.xt
=> GH-2557: Error on property access if type is a composition with any+

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/editor/contentassist/N4JSContentAssistContextFactory.java, tests/org.eclipse.n4js.xpect.tests/xt-tests/contentassist/GH_2569a.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/contentassist/GH_2569b.n4js.xt
=> GH-2569: Content assist not working at specific location in code

plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/TypeReferenceTransformation.java, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/OptionalMembers.n4js.xt
=> GH-2575: Optionality on fields in object literals gets lost in d.ts output

plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/TypeReferenceTransformation.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtIdeTest.java, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/ReadonlyStructuralTypes_TS_circularity.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/ReadonlyStructuralTypes_TS_circularity.n4jsd.xt
=> GH-2576: TypeScript's meta type language has issues with circular type structures

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/N4jscModule.java, plugins/org.eclipse.n4js.json.ide/src/org/eclipse/n4js/json/ide/codeActions/JSONCodeActionService.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/languages/N4LanguageUtils.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/xtext/serializer/SerializerPatchModule.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/N4jscTestFactory.java, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/N4JSInjectorProviderWithIndex.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/YarnProjectDuplicateNames.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/xtext/server/ChunkedResourceDescriptionsTest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/dirtystate/BuilderParticipantIdeTest.java, tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/tests/dirtystate/testdata/StaticTestFiles.java
=> GH-2586: Small enhancements fixed in between

plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSGlobals.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/CliTools.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/TestProcessBuilder.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/TestProcessExecuter.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/utils/BinariesConstants.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/utils/BinariesLocatorHelper.java
closes #2592
also: migration to pnpm in internal integration tests
=> GH-2592: As a smith I want to update node in the docker image (and fix extended tests)

plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/NodeModulesDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/TestWorkspaceManager.java, testhelpers/org.eclipse.n4js.tests.helper/src/org/eclipse/n4js/tests/helper/mock/MockWorkspaceSupplier.java, tests/org.eclipse.n4js.ide.tests/PDTs/pnpmDependency1.pdt, tests/org.eclipse.n4js.ide.tests/PDTs/pnpmDependency2.pdt, tests/org.eclipse.n4js.ide.tests/PDTs/pnpmSimple1.pdt, tests/org.eclipse.n4js.ide.tests/PDTs/pnpmSimple2.pdt, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderCopiedProjectTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/buildorder/AbstractBuildOrderTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/buildorder/BuildOrderDependenciesTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/codeActions/OrganizeImportsAddMissingTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/projectdiscovery/CreateProjectStructureUtils.java
=> GH-2588: Exported d.ts files contain non-public elements

plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/print/PrettyPrinterDts.java, plugins/org.eclipse.n4js.utils/src/org/eclipse/n4js/utils/URIUtils.java, testhelpers/org.eclipse.n4js.ide.tests.helper/src/org/eclipse/n4js/ide/tests/helper/server/xt/XtIdeTest.java, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/cutOffReferences/ReferenceToNonDtsProject.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/BareImport.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/DefaultAsImport.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ImportForLiteralType1.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ImportForLiteralType2.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ImportMustBeAdded1.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ImportMustBeAdded2_withAlias.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ImportMustBeAdded3_forIndirectlyExportedElem.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ImportWithExtension.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/ModuleSpecifiers.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/NamespaceAccess.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/imports/UseExistingNamespaceImport.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/inferredTypes/InferredTypes2.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/inferredTypes/InferredTypesImportUsedInStatement.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/inferredTypes/ReplaceWildcard.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/dts-export/inferredTypes/UpperBounds.n4js.xt
=> GH-2595: The d.ts export should append .js file extensions in import statements

plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDescriptionLoader.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/AbstractPackageJSONValidatorExtension.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/dts/tests/TsConfigRespectTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/WorkspaceNoDefaultSourceFolderPnpmTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/WorkspaceNoDefaultSourceFolderYarnTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/YarnDifferentPackageNamesTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/YarnProjectDuplicateNamesTest.java, tests/org.eclipse.n4js.lang.tests/src/org/eclipse/n4js/tests/packagejson/PackageJsonHelperTest.java
=> GH-2606: A workspace project should not have the its root folder as a default source folder

plugins/org.eclipse.n4js/src/org/eclipse/n4js/tooling/react/ReactHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/N4JSXValidator.xtend, tests/org.eclipse.n4js.spec.tests/xt-tests/FunctionReactNode.n4jsx.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Req241116_JSXElements_Referring_to_React_Components.n4jsx.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/react/index.n4jsd, tests/org.eclipse.n4js.spec.tests/xt-tests/reactWithModifications/index.n4jsd, tests/org.eclipse.n4js.xpect.tests/react-implementations/valid/index.n4jsd, tests/org.eclipse.n4js.xpect.tests/xt-tests/scoping/n4jsx/ClassComponentDescriptions.n4jsx.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/scoping/n4jsx/FunctionComponentDescriptions.n4jsx.xt
=> GH-2614: N4JSX should accept functions that return ReactNodes

plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/JSXTransformation.java, tests/org.eclipse.n4js.spec.tests/xt-tests/react_transpile/jsx_transpile_properties.n4jsx.xt
=> GH-2625: Previous JSX performance enhancement causes runtime warnings

plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/ParameterizedTypeRefStructuralImpl.java, plugins/org.eclipse.n4js.ts.model/emf-gen/org/eclipse/n4js/ts/typeRefs/impl/StructuralTypeRefImpl.java, plugins/org.eclipse.n4js.ts.model/model/TypeRefs.xcore, plugins/org.eclipse.n4js/src/org/eclipse/n4js/postprocessing/PolyProcessor_FunctionExpression.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/SubtypeJudgment.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/constraints/Reducer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/StructuralTypingComputer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/SubtypeComputer.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/typesystem/utils/TypeSystemHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/ProjectDiscoveryHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/IssueCodes.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/utils/N4JSPackageName.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/buildorder/BuildOrderToDtsTest.java, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch05_01_06__DefinitionSiteVariance/Req51_DefinitionSiteVariance_builtInTypes.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch09_02_03__for_of_statement/forOf_TypeOfContents.n4js.xt, tests/org.eclipse.n4js.spec.tests/xt-tests/Ch09_02_03__for_of_statement/forOf_expectedTypeOfIterable.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/dts-import/user-tests/explicit_subtype_rules.n4js.xt, tests/org.eclipse.n4js.xpect.tests/xt-tests/typesystem/Wildcards_StructTyping_useCaseIterable.n4js.xt
=> GH-2633: As a developer I want to use d.ts definitions of redux/-saga

plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/N4JSStatefulIncrementalBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/DefaultBuildRequestFactory.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/ProjectBuilder.java, plugins/org.eclipse.n4js.xtext/src/org/eclipse/n4js/xtext/workspace/BuildOrderIterator.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/CyclicDependenciesBuilderNoRebuildTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/CyclicDependenciesBuilderTest.java
=> GH-2636: Improve handling of dependency cycles within dependencies

plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscCompiler.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscLanguageClient.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/DtsAfterBuildListener.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/build/N4JSBuildOrderInfoComputer.java, plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/commands/N4JSCommandService.java, plugins/org.eclipse.n4js.transpiler.dts/src/org/eclipse/n4js/transpiler/dts/transform/ModuleSpecifierTransformationDts.java, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/CommonJsImportsTransformation.java, plugins/org.eclipse.n4js.transpiler.es/src/org/eclipse/n4js/transpiler/es/transform/ModuleSpecifierTransformation.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/LanguageServerFrontend.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/BuilderFrontend.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/LspProgessUtil.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XWorkspaceBuilder.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/build/XWorkspaceManager.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/PackageJsonHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/packagejson/projectDescription/ProjectReference.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/accessModifiers/AbstractTypeVisibilityChecker.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/tooling/compare/ApiImplMapping.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/tooling/compare/ProjectCompareHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageHelper.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/validation/validators/packagejson/N4JSProjectSetupJsonValidatorExtension.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfig.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSProjectConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/N4JSWorkspaceConfigSnapshot.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/WorkspaceAccess.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/workspace/utils/SemanticDependencySupplier.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/builder/IncrementalBuilderGenerateTest.java, tests/org.eclipse.n4js.ide.tests/src/org/eclipse/n4js/ide/tests/server/CommandRebuildTest.java
=> GH-2638: Improve progress logging during initialisation and check performance

n4js-libs/package.json, n4js-libs/packages/n4js-cli/src/n4js/JreProvider.n4js, n4js-libs/packages/org.eclipse.n4js.mangelhaft/src/n4js/org/eclipse/n4js/mangelhaft/TestController.n4js, n4js-libs/yarn.lock, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscIssueSerializer.java, plugins/org.eclipse.n4js.cli/src/org/eclipse/n4js/cli/compiler/N4jscLanguageClient.java, plugins/org.eclipse.n4js.xtext.ide/src/org/eclipse/n4js/xtext/ide/server/XLanguageServerImpl.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/N4JSGlobals.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/scoping/utils/ProjectImportEnablingScope.java, plugins/org.eclipse.n4js/src/org/eclipse/n4js/utils/N4JSLanguageHelper.java, testhelpers/org.eclipse.n4js.cli.tests.helper/src/org/eclipse/n4js/cli/helper/N4jscTestLanguageClient.java, tests/org.eclipse.n4js.integration.tests/src/org/eclipse/n4js/integration/tests/cli/compile/AT_GH_2154_HeadlessBuilderNotShowingAllIssuesTest.java, tests/org.eclipse.n4js.integration.tests/src/org/eclipse/n4js/integration/tests/cli/compile/N4jscInitTest.java
=> GH-2641: Bump js related versions in dockerfile
